/**
 * Lebanese Administrative Divisions: Mohafaza → Qada → Village
 * 
 * Data sourced from EbrahimKaram/Lebanese-Villages-List (GPL-3.0)
 * cross-referenced with OCHA COD-AB Lebanon administrative boundaries.
 * 
 * Structured for potential extraction as standalone npm package.
 * ~1,100 villages across 26 districts and 8 governorates.
 */

export interface Division {
  slug: string;
  ar: string;
  en: string;
}

export interface QadaWithVillages {
  qada: Division;
  villages: Division[];
}

export interface MohafazaWithQadas {
  mohafaza: Division;
  qadas: QadaWithVillages[];
}

export const LEBANON_DIVISIONS: MohafazaWithQadas[] = [
  {
    mohafaza: { slug: "beirut", ar: "بيروت", en: "Beirut" },
    qadas: [
      {
        qada: { slug: "beirut", ar: "بيروت", en: "Beirut" },
        villages: [
          { slug: "achrafieh", ar: "الاشرفية", en: "Achrafieh" },
          { slug: "ain_el_mreisse", ar: "دار المريسة", en: "Ain el-Mreissé" },
          { slug: "bachoura", ar: "الباشورة", en: "Bachoura" },
          { slug: "mazraa", ar: "المزرعة", en: "Mazraa" },
          { slug: "medawar", ar: "المدور", en: "Medawar" },
          { slug: "minet_el_hosn", ar: "ميناء الحصن", en: "Minet el-Hosn" },
          { slug: "moussaytbeh", ar: "المصيطبة", en: "Moussaytbeh" },
          { slug: "port", ar: "المرفأ", en: "Port" },
          { slug: "ras_beyrouth", ar: "رأس بيروت", en: "Ras Beyrouth" },
          { slug: "remeil", ar: "الرميل", en: "Remeil" },
          { slug: "saife", ar: "الصيفي", en: "Saifé" },
          { slug: "zoukak_el_blatt", ar: "زقاق البلاط", en: "Zoukak el-Blatt" },
        ],
      },
    ],
  },
  {
    mohafaza: { slug: "mount_lebanon", ar: "جبل لبنان", en: "Mount Lebanon" },
    qadas: [
      {
        qada: { slug: "baabda", ar: "بعبدا", en: "Baabda" },
        villages: [
          { slug: "ain_mouaffak", ar: "عين موفق", en: "Aïn Mouaffak" },
          { slug: "araya", ar: "عاراي", en: "Araya" },
          { slug: "arsoune", ar: "ارصون", en: "Arsoune" },
          { slug: "baabda", ar: "بعبدا", en: "Baabda" },
          { slug: "baalchemay", ar: "بعلشميه", en: "Baalchemay" },
          { slug: "bmariam", ar: "بمريم", en: "Bmariam" },
          { slug: "borge_el_baragenat", ar: "برج البراجنة حي السنديان", en: "Borge el Baragenat" },
          { slug: "boutchay", ar: "بطشيه", en: "Boutchay" },
          { slug: "btebiat", ar: "بتبيات", en: "Btebiat" },
          { slug: "btekhnay", ar: "بتخنيه", en: "Btekhnay" },
          { slug: "bzebdine", ar: "بزبدين", en: "Bzebdine" },
          { slug: "chbaniyeh", ar: "الشبانيه", en: "Chbaniyeh" },
          { slug: "chiah", ar: "الشياح بئر العبد", en: "Chiah" },
          { slug: "chouit", ar: "شويت", en: "Chouit" },
          { slug: "deir_el_harf", ar: "دير الحرف", en: "Deir El-Harf" },
          { slug: "deir_khouna", ar: "دير خونا", en: "Deir Khouna" },
          { slug: "el_abadiyeh", ar: "العباديه", en: "El-Abadiyeh" },
          { slug: "el_dleibe", ar: "الدليبه", en: "El-Dleibé" },
          { slug: "el_khalouat", ar: "الخلوات", en: "El-Khalouat" },
          { slug: "el_kraye", ar: "القريه", en: "El-Krayé" },
          { slug: "el_ksaibeh", ar: "القصيبه", en: "El-Ksaibeh" },
          { slug: "falougha", ar: "فالوغا", en: "Falougha" },
          { slug: "hammana", ar: "حمانا", en: "Hammana" },
          { slug: "haret_el_sit", ar: "حارة الست", en: "Haret -el-Sit" },
          { slug: "haret_hamze", ar: "حارة حمزه", en: "Haret Hamzé" },
          { slug: "haret_horaik", ar: "حارة حريك حي الرويس", en: "Haret Horaïk" },
          { slug: "hasbaya_el_meten", ar: "حاصبيا المتن", en: "Hasbaya-el Meten" },
          { slug: "jouar_el_haouz", ar: "جوار الحوز", en: "Jouar el Haouz" },
          { slug: "jouret_arsoune", ar: "جورة ارصون", en: "Jouret Arsoune" },
          { slug: "kartada", ar: "قرطاضة", en: "Kartada" },
          { slug: "kernayel", ar: "قرنايل", en: "Kernayel" },
          { slug: "kfar_selouane", ar: "كفرسلوان", en: "Kfar Selouane" },
          { slug: "kfarchima", ar: "كفرشيما", en: "Kfarchima" },
          { slug: "kobbai", ar: "كوبا", en: "Kobbaï" },
          { slug: "ktale", ar: "قتاله", en: "Ktalé" },
          { slug: "laylaki", ar: "الليلكه", en: "Laylaki" },
          { slug: "mardachat", ar: "المرداشة", en: "Mardachat" },
          { slug: "ras_el_meten", ar: "راس المتن", en: "Ras el Meten" },
          { slug: "ras_el_harf", ar: "راس الحرف", en: "Ras-el-Harf" },
          { slug: "roueissat_el_ballout", ar: "رويسة البلوط", en: "Roueissat-el-Ballout" },
          { slug: "salima", ar: "صليما", en: "Salima" },
          { slug: "tahouitat_el_ghadir", ar: "تحويطة الغدير", en: "Tahouitat-el-Ghadir" },
          { slug: "tarchiche", ar: "ترشيش", en: "Tarchiche" },
          { slug: "wadi_chahrour_el_olia", ar: "وادي شحرور العليا", en: "Wadi Chahrour el Olia" },
          { slug: "wadi_chahrour_el_soufla", ar: "وادي شحرور السفلى", en: "Wadi Chahrour el Soufla" },
          { slug: "zandouka", ar: "زندوقه", en: "Zandouka" },
        ],
      },
      {
        qada: { slug: "aley", ar: "عاليه", en: "Aley" },
        villages: [
          { slug: "abey", ar: "عبيه", en: "Abey" },
          { slug: "aghmide", ar: "اغميد", en: "Aghmide" },
          { slug: "ain_drafile", ar: "عين درافيل", en: "Aïn Drafile" },
          { slug: "ain_el_halzoune", ar: "عين الحلزون", en: "Aïn El-Halzoune" },
          { slug: "ain_ksour", ar: "عين كسور", en: "Aïn Ksour" },
          { slug: "ain_saideh", ar: "عين السيدة", en: "Ain Saideh" },
          { slug: "ain_sofar", ar: "صوفر", en: "Aïn Sofar" },
          { slug: "ain_traz", ar: "عين تراز", en: "Aïn Traz" },
          { slug: "ain_dara", ar: "عين داره", en: "Aïn-Dara" },
          { slug: "ain_el_jdeide", ar: "عين الجديدة", en: "Aïn-El-Jdeidé" },
          { slug: "ain_enoub", ar: "عين عنوب", en: "Aïn-Enoub" },
          { slug: "ainab", ar: "عيناب", en: "Aïnab" },
          { slug: "aitate", ar: "عيتات", en: "Aïtate" },
          { slug: "aley", ar: "عاليه شمالي", en: "Aley" },
          { slug: "aramoun", ar: "عرمون", en: "Aramoun" },
          { slug: "baouarta", ar: "بعورته", en: "Baouarta" },
          { slug: "bchamoune", ar: "بشامون", en: "Bchamoune" },
          { slug: "bdedoune", ar: "بدادون", en: "Bdédoune" },
          { slug: "bedghane", ar: "بدغان", en: "Bedghane" },
          { slug: "bhamdoun_village", ar: "بحمدون", en: "Bhamdoun (Village)" },
          { slug: "bhouara", ar: "بحواره", en: "Bhouara" },
          { slug: "bisrine", ar: "بسرين", en: "Bisrine" },
          { slug: "bkhichtay", ar: "بخشتيه", en: "Bkhichtay" },
          { slug: "bleibel", ar: "بليبل", en: "Bleibel" },
          { slug: "bmakkine", ar: "بمكين", en: "Bmakkine" },
          { slug: "bmehrai", ar: "بمهريه", en: "Bmehraï" },
          { slug: "bouzride", ar: "بوزريده", en: "Bouzridé" },
          { slug: "bsous", ar: "بسوس", en: "Bsous" },
          { slug: "btater", ar: "بتاتر", en: "Btater" },
          { slug: "chamlane", ar: "شملان", en: "Chamlane" },
          { slug: "chanay", ar: "شانيه", en: "Chanay" },
          { slug: "charoun", ar: "شارون", en: "Charoun" },
          { slug: "chartoun", ar: "شرتون", en: "Chartoun" },
          { slug: "chouaifat_amroussyat", ar: "الشويفات حي العمروسية", en: "Chouaifat Amroussyat" },
          { slug: "chouaifat_oumara", ar: "الشويفات حي الامراء", en: "Chouaifat Oumara" },
          { slug: "chouaifat_qobbat", ar: "الشويفات حي القبة", en: "Chouaifat Qobbat" },
          { slug: "dakkoun", ar: "دقون", en: "Dakkoun" },
          { slug: "deir_koubel", ar: "دير قوبل", en: "Deir-Koubel" },
          { slug: "dfoun", ar: "دفون", en: "Dfoun" },
          { slug: "douair_el_roummane", ar: "دوير الرمان", en: "Douair El-Roummane" },
          { slug: "el_azouniyeh", ar: "العزونية", en: "EL-Azouniyeh" },
          { slug: "el_bennaye", ar: "البنيه", en: "El-Bennayé" },
          { slug: "el_ghaboun", ar: "الغابون", en: "El-Ghaboun" },
          { slug: "el_mansouriyeh_et_ain_el_marge", ar: "عين المرج", en: "El-Mansouriyeh et Aïn-El-Marge" },
          { slug: "el_mechrefeh", ar: "المشرفه", en: "El-Mechrefeh" },
          { slug: "el_mreijate", ar: "المريجات", en: "El-Mreijate" },
          { slug: "el_ramliyeh", ar: "الرمليه", en: "El-Ramliyeh" },
          { slug: "habramoun", ar: "حبرامون", en: "Habramoun" },
          { slug: "houmale", ar: "حومال", en: "Houmale" },
          { slug: "kaifoun", ar: "كفون", en: "Kaïfoun" },
          { slug: "kfar_matta", ar: "كفرمتى", en: "Kfar Matta" },
          { slug: "kfar_aammay", ar: "كفر عميه", en: "Kfar-Aammay" },
          { slug: "maasraiti", ar: "معصريتي", en: "Maasraïti" },
          { slug: "majdel_baana", ar: "مجدل بعنا", en: "Majdel Baana" },
          { slug: "mazraet_el_nahr", ar: "مزرعة النهر", en: "Mazraet El-Nahr" },
          { slug: "mejdlaya", ar: "مجدلايا", en: "Mejdlaya" },
          { slug: "rechmaya", ar: "رشميا", en: "Rechmaya" },
          { slug: "remhala", ar: "رمحالا", en: "Remhala" },
          { slug: "roueissat_el_naaman", ar: "رويسة النعمان", en: "Roueissat El-Naaman" },
          { slug: "sarahmoul", ar: "سرحمول", en: "Sarahmoul" },
          { slug: "selfaya", ar: "سلفايا", en: "Selfaya" },
          { slug: "souk_el_gharb", ar: "سوق الغرب", en: "Souk-El-Gharb" },
        ],
      },
      {
        qada: { slug: "chouf", ar: "الشوف", en: "Chouf" },
        villages: [
          { slug: "ain_keni", ar: "عين قني", en: "Aïn Kéni" },
          { slug: "ain_ouzai", ar: "عين وزين", en: "Aïn Ouzaï" },
          { slug: "ain_zhalta", ar: "عين زحلتا", en: "Aïn Zhalta" },
          { slug: "almane", ar: "علمان", en: "Almane" },
          { slug: "ammatour", ar: "عماطور", en: "Ammatour" },
          { slug: "ammik", ar: "عميق", en: "Ammik" },
          { slug: "anbal", ar: "البطال", en: "Anbal" },
          { slug: "anoute", ar: "عانوت", en: "Anoute" },
          { slug: "atrine", ar: "عترين", en: "Atrine" },
          { slug: "baadarane", ar: "بعذران", en: "Baadarane" },
          { slug: "baakline", ar: "بعقلين التحتا", en: "Baakline" },
          { slug: "baassir", ar: "بعاصير", en: "Baassir" },
          { slug: "baikoun", ar: "بيقون", en: "Baïkoun" },
          { slug: "barja", ar: "برجا", en: "Barja" },
          { slug: "bater", ar: "باتر", en: "Bater" },
          { slug: "batloune", ar: "بطلون", en: "Batloune" },
          { slug: "bchatfine", ar: "بشتفين", en: "Bchatfine" },
          { slug: "beit_eddine", ar: "بيت الدين", en: "Beit Eddine" },
          { slug: "benouaiti", ar: "بنويتي", en: "Benouaïti" },
          { slug: "botme", ar: "بطمه", en: "Botmé" },
          { slug: "brih_et_mteile", ar: "بريح", en: "Brih et Mteilé" },
          { slug: "bsaba", ar: "بسابا", en: "Bsaba" },
          { slug: "chehime", ar: "شحيم حي البدوي", en: "Chehime" },
          { slug: "chourite", ar: "شوريت", en: "Chourite" },
          { slug: "dahr_el_mghara", ar: "ضهر المغارة", en: "Dahr El-Mghara" },
          { slug: "dalhoune", ar: "دلهون", en: "Dalhoune" },
          { slug: "damour", ar: "الدامور", en: "Damour" },
          { slug: "daraya", ar: "داريا", en: "Daraya" },
          { slug: "deir_baba", ar: "دير بابا", en: "Deir Baba" },
          { slug: "deir_couche", ar: "دير كوشه", en: "Deir Couché" },
          { slug: "deir_el_kamar", ar: "دير القمر", en: "Deir El-Kamar" },
          { slug: "dmite", ar: "دميت", en: "Dmite" },
          { slug: "el_jiyeh", ar: "الجيه", en: "El Jiyeh" },
          { slug: "el_barouk", ar: "الباروك", en: "El-Barouk" },
          { slug: "el_berjaine", ar: "البرجين", en: "El-Berjaine" },
          { slug: "el_jleiliyeh", ar: "الجليليه", en: "El-Jleiliyeh" },
          { slug: "el_maaniyeh", ar: "المعنيه", en: "El-Maaniyeh" },
          { slug: "el_mouchref", ar: "المشرف", en: "El-Mouchref" },
          { slug: "el_moukhtara", ar: "المختارة", en: "El-Moukhtara" },
          { slug: "el_wardaniyeh", ar: "الوردانية", en: "El-Wardaniyeh" },
          { slug: "el_werhaniyeh", ar: "الورهانية", en: "El-Werhaniyeh" },
          { slug: "gharife", ar: "غريفه", en: "Gharifé" },
          { slug: "haret_jandal", ar: "حارة جندل", en: "Haret Jandal" },
          { slug: "hasroute", ar: "حصروت", en: "Hasroute" },
          { slug: "jadra", ar: "جدرا - وادي الزينة", en: "Jadra" },
          { slug: "jmeiliyeh", ar: "الجميليه", en: "Jmeiliyeh" },
          { slug: "joun", ar: "جون", en: "Joun" },
          { slug: "katermaya", ar: "كترمايا", en: "Katermaya" },
          { slug: "kfar_fakoud", ar: "كفر فاقود", en: "Kfar Fakoud" },
          { slug: "kfar_katra", ar: "كفر قطره", en: "Kfar Katra" },
          { slug: "kfar_nabrakh", ar: "كفرنبرخ", en: "Kfar Nabrakh" },
          { slug: "kfarhime", ar: "كفرحيم", en: "Kfarhime" },
          { slug: "kfarnice", ar: "كفرنيس", en: "Kfarnice" },
          { slug: "kherbet_bisri", ar: "خربة بسري", en: "Kherbet Bisri" },
          { slug: "kraya", ar: "كفرحي", en: "Kraya" },
          { slug: "maasser_beit_eddine", ar: "معاصر بيت الدين", en: "Maasser Beit Eddine" },
          { slug: "maasser_el_chouf", ar: "معاصر الشوف", en: "Maasser el-Chouf" },
          { slug: "majdalouna", ar: "مجدلونا", en: "Majdalouna" },
          { slug: "majdel_meouche", ar: "مجدل المعوش", en: "Majdel Meouche" },
          { slug: "mazboud", ar: "مزبود", en: "Mazboud" },
          { slug: "mazmoura", ar: "مزموره", en: "Mazmoura" },
          { slug: "mazraet_el_chouf", ar: "مزرعة الشوف", en: "Mazraet El-Chouf" },
          { slug: "mazraet_el_dahr", ar: "مزرعة الضهر", en: "Mazraet El-Dahr" },
          { slug: "mriste", ar: "مرستي", en: "Mristé" },
          { slug: "mtoulle_bzina", ar: "المطله", en: "Mtoullé Bzina" },
          { slug: "rmeileh", ar: "الرميله", en: "Rmeileh" },
          { slug: "sebline", ar: "سبلين", en: "Sebline" },
          { slug: "sirjbal", ar: "سرجبال", en: "Sirjbal" },
          { slug: "wadi_bnahley", ar: "وادي بنحليه", en: "Wadi Bnahley" },
          { slug: "wadi_el_deir", ar: "وادي الدير", en: "Wadi El-Deir" },
          { slug: "wadi_el_sit", ar: "وادي الست", en: "Wadi El-Sit" },
          { slug: "zaarouriyeh", ar: "الزعرورية", en: "Zaarouriyeh" },
        ],
      },
      {
        qada: { slug: "matn", ar: "المتن", en: "Matn" },
        villages: [
          { slug: "abou_mizane", ar: "ابو ميزان", en: "Abou-Mizane" },
          { slug: "ain_el_zeitoune", ar: "عين الزيتونه", en: "Aïn -El-Zeitouné" },
          { slug: "ain_aar", ar: "عين عار", en: "Aïn Aar" },
          { slug: "ain_el_kabou", ar: "عين القبو ودير مار سمعان", en: "Aïn El-Kabou" },
          { slug: "ain_alak", ar: "عين علق", en: "Aïn-Alak" },
          { slug: "ain_el_kharroube", ar: "عين الخروبه", en: "Aïn-El-Kharroubé" },
          { slug: "ain_el_safsaf", ar: "عين الصفصاف", en: "Aïn-El-Safsaf" },
          { slug: "ain_el_sindiane", ar: "عين السنديانه", en: "Aïn-El-Sindiané" },
          { slug: "ain_el_teffaha", ar: "عين التفاحة", en: "Aïn-el-Teffaha" },
          { slug: "ain_saade", ar: "عين سعادة", en: "Aïn-Saâdé" },
          { slug: "airoune", ar: "العيرون", en: "Aïroune" },
          { slug: "antelias", ar: "انطلياس", en: "Antélias" },
          { slug: "antoura", ar: "عينطوره", en: "Antoura" },
          { slug: "baabdat_et_sfaile", ar: "بعبدات", en: "Baabdat et Sfaïlé" },
          { slug: "baouchariat", ar: "البوشريه", en: "Baouchariat" },
          { slug: "baskinta", ar: "بسكنتا جنوبي,بسكنتا شمالي", en: "Baskinta" },
          { slug: "beit_chebab", ar: "بيت شباب تحتاني", en: "Beit Chebab" },
          { slug: "beit_el_koukou", ar: "بيت الككو", en: "Beit El Koukou" },
          { slug: "beit_mery", ar: "بيت مري", en: "Beit Mery" },
          { slug: "biakoute", ar: "بياقوت", en: "Biakoute" },
          { slug: "bikfaya", ar: "بكفيا", en: "Bikfaya" },
          { slug: "bkennaya", ar: "بقنايا", en: "Bkennaya" },
          { slug: "borge_hammoud", ar: "برج حمود", en: "Borge Hammoud" },
          { slug: "broummana", ar: "برمانا", en: "Broummana" },
          { slug: "bsalime", ar: "بصاليم", en: "Bsalime" },
          { slug: "bteghrine", ar: "بتغرين", en: "Bteghrine" },
          { slug: "chaouie_knaitre_et_mar_gergesse_bhurdok", ar: "الشاويه والقنيطره", en: "Chaouié, Knaitré et Mar gergesse Bhurdok" },
          { slug: "chouaya", ar: "شويا", en: "Chouaya" },
          { slug: "choueir", ar: "الشوير", en: "Choueir" },
          { slug: "chrine", ar: "شرين", en: "Chrine" },
          { slug: "dahr_el_souwan", ar: "ضهر الصوان", en: "Dahr El Souwan" },
          { slug: "dbaye", ar: "الضبيه", en: "Dbayé" },
          { slug: "deir_chamra", ar: "دير شمرا", en: "Deir Chamra" },
          { slug: "dekouanet", ar: "الدكوانه", en: "Dekouanet" },
          { slug: "dik_el_mehdi", ar: "ديك المحدي", en: "Dik El-Mehdi" },
          { slug: "douar", ar: "الدوار", en: "Douar" },
          { slug: "el_freike", ar: "الفريكه", en: "El Freiké" },
          { slug: "el_mtein", ar: "المتين", en: "El Mtein" },
          { slug: "el_atchane", ar: "العطشانه", en: "El-Atchané" },
          { slug: "el_dechouniyeh", ar: "الديشونيه", en: "El-Dechouniyeh" },
          { slug: "el_jouar", ar: "الجوار", en: "El-Jouar" },
          { slug: "el_khelle", ar: "الخله", en: "El-Khellé" },
          { slug: "el_khounchara", ar: "الخنشاره", en: "El-Khounchara" },
          { slug: "el_mansouriyeh", ar: "المنصوريه", en: "El-Mansouriyeh" },
          { slug: "el_mayasse", ar: "المياسه", en: "El-Mayassé" },
          { slug: "el_mhaidce", ar: "المحيدثة", en: "El-Mhaidcé" },
          { slug: "el_mrouge", ar: "المروج", en: "El-Mrouge" },
          { slug: "el_mtaileb", ar: "المطيلب", en: "El-Mtaileb" },
          { slug: "el_sfaile", ar: "السفيله", en: "El-Sfailé" },
          { slug: "el_zalka", ar: "الزلقا", en: "El-Zalka" },
          { slug: "fanar", ar: "فنار", en: "Fanar" },
          { slug: "hemlaya", ar: "حملايا", en: "Hemlaya" },
          { slug: "jal_el_dib", ar: "جل الديب", en: "Jal-el-Dib" },
          { slug: "jodaidat", ar: "الجديدة", en: "Jodaidat" },
          { slug: "jouret_el_ballout", ar: "جورة البلوط", en: "Jouret-El-Ballout" },
          { slug: "kaakour", ar: "القعقور", en: "Kaakour" },
          { slug: "kanabet_broummana", ar: "قنابة برمانا", en: "Kanabet Broummana" },
          { slug: "kannabet_salima", ar: "قنابة صليما", en: "Kannabet Salima" },
          { slug: "kfar_akab", ar: "كفر عقاب", en: "Kfar Akab" },
          { slug: "kfartai", ar: "كفرتيه", en: "Kfartaï" },
          { slug: "kornet_chahouane", ar: "قرنة شهوان", en: "Kornet Chahouane" },
          { slug: "kornet_el_hamra", ar: "قرنة الحمرا", en: "Kornet-El-Hamra" },
          { slug: "majdel_tarchiche", ar: "مجدل ترشيش", en: "Majdel Tarchiche" },
          { slug: "mar_boutros_karm_el_tine", ar: "مار بطرس كرم التين", en: "Mar Boutros Karm El-Tine" },
          { slug: "mar_chaya_et_mzakki", ar: "مار شعيا والمزكه", en: "Mar Chaya et Mzakki" },
          { slug: "mar_mikhael_bnabil", ar: "مار مخايل بنابيل", en: "Mar Mikhael Bnabil" },
          { slug: "mar_mousa_el_douar", ar: "مار موسى الدوار", en: "Mar Mousa-El-Douar" },
          { slug: "marjaba", ar: "مرجبا", en: "Marjaba" },
          { slug: "maska_et_el_ghabeh", ar: "الغابه,المسقى", en: "Maska et El-Ghabeh" },
          { slug: "mazraet_beit_chaar", ar: "بيت الشعار", en: "Mazraet Beit Chaar" },
          { slug: "mazraet_deir_aoukar", ar: "عوكر", en: "Mazraet Deir Aoukar" },
          { slug: "mazraet_yachou", ar: "مزرعة يشوع", en: "Mazraet Yachou" },
          { slug: "mchikha", ar: "مشيخا", en: "Mchikha" },
          { slug: "mezher", ar: "مزهر ومجدوب", en: "Mezher" },
          { slug: "mkallesse", ar: "المكلس", en: "Mkallesse" },
          { slug: "nabiyeh", ar: "نابيه", en: "Nabiyeh" },
          { slug: "naccache", ar: "النقاش", en: "Naccache" },
          { slug: "roumieh", ar: "روميه", en: "Roumieh" },
          { slug: "sakiet_el_misk_et_bhorsaf", ar: "ساقية المسك,بحر صاف", en: "Sakiet-El-Misk et Bhorsaf" },
          { slug: "senn_el_fil", ar: "سن الفيل حي البلده", en: "Senn el Fil" },
          { slug: "wadi_chahine", ar: "وادي شاهين", en: "Wadi Chahine" },
          { slug: "wadi_el_karm", ar: "وادي الكرم", en: "Wadi El-Karm" },
          { slug: "wata_amaret_chalhoub", ar: "عمارة شلهوب", en: "Wata Amaret Chalhoub" },
          { slug: "wata_el_mrouge", ar: "وطى المروج", en: "Wata El-Mrouge" },
          { slug: "zabbougha", ar: "زبوغا", en: "Zabbougha" },
          { slug: "zacrite", ar: "زكريت", en: "Zacrite" },
          { slug: "zaraoune", ar: "زرعون", en: "Zaraoune" },
          { slug: "zouk_khrab", ar: "زوق الخراب ومار يوسف", en: "Zouk-Khrab" },
        ],
      },
      {
        qada: { slug: "keserwan", ar: "كسروان", en: "Keserwan" },
        villages: [
          { slug: "achkoute", ar: "عشقوت", en: "Achkoute" },
          { slug: "adma_defneh", ar: "ادما والدفنه", en: "Adma-Defneh" },
          { slug: "ain_el_rihane", ar: "عين الريحانه", en: "Aïn El-Rihané" },
          { slug: "ajeltoun", ar: "عجلتون", en: "Ajeltoun" },
          { slug: "balloune", ar: "بلونه", en: "Ballouné" },
          { slug: "batha", ar: "بطحا", en: "Batha" },
          { slug: "bekaatet_kenaan", ar: "بقعاتة كنعان", en: "Bekaatet Kénaan" },
          { slug: "bekaatet_achkoute", ar: "بقعاتة عشقوت", en: "Bekaatet-Achkoute" },
          { slug: "bekaatouta", ar: "بقعتوته", en: "Bekaatouta" },
          { slug: "bezhel", ar: "بزحل", en: "Bezhel" },
          { slug: "bzoumar", ar: "بزمار", en: "Bzoumar" },
          { slug: "chahtoul", ar: "شحتول", en: "Chahtoul" },
          { slug: "chenanhir", ar: "شننعير", en: "Chenanhir" },
          { slug: "daraoun", ar: "درعون", en: "Daraoun" },
          { slug: "djounie_ghadir", ar: "غادير", en: "Djounié Ghadir" },
          { slug: "dlebta", ar: "دلبتا", en: "Dlebta" },
          { slug: "eghbeh", ar: "اغبه", en: "Eghbeh" },
          { slug: "el_azra", ar: "العذرا", en: "El-Azra" },
          { slug: "el_bouar", ar: "البوار", en: "El-Bouar" },
          { slug: "el_ekaibe", ar: "العقيبه", en: "El-Ekaïbé" },
          { slug: "el_ghuine", ar: "الغينه", en: "El-Ghuiné" },
          { slug: "el_hossein", ar: "الحصين", en: "El-Hossein" },
          { slug: "el_kfour", ar: "الكفور", en: "El-Kfour" },
          { slug: "el_mouaisra", ar: "المعيصرة", en: "El-Mouaïsra" },
          { slug: "el_mradiyeh", ar: "المراديه", en: "El-Mradiyeh" },
          { slug: "el_safra", ar: "الصفرا", en: "EL-Safra" },
          { slug: "faitroun", ar: "فيطرون", en: "Faïtroun" },
          { slug: "faraya", ar: "فاريا", en: "Faraya" },
          { slug: "fatka", ar: "فتقا", en: "Fatka" },
          { slug: "ghazir", ar: "غزير الجامع", en: "Ghazir" },
          { slug: "ghbele", ar: "غباله", en: "Ghbélé" },
          { slug: "ghodrace", ar: "غدراس", en: "Ghodrace" },
          { slug: "ghosta", ar: "غوسطا", en: "Ghosta" },
          { slug: "harissa", ar: "حريصا", en: "Harissa" },
          { slug: "hayata", ar: "حياطه", en: "Hayata" },
          { slug: "herhraya_et_kattine", ar: "هرهريا والقطين", en: "Herhraya et Kattine" },
          { slug: "hrajel", ar: "حراجل", en: "Hrajel" },
          { slug: "jdeidet_ghazir", ar: "جديدة غزير", en: "Jdeidet Ghazir" },
          { slug: "jeita", ar: "جعيتا", en: "Jeita" },
          { slug: "jounieh_haret_sakhr", ar: "حارة صخر", en: "Jounieh Haret Sakhr" },
          { slug: "jouret_bedrane", ar: "جورة بدران", en: "Jouret Bedrane" },
          { slug: "jouret_termos", ar: "جورة الترمس", en: "Jouret Termos" },
          { slug: "kfar_yassine", ar: "كفرياسين", en: "Kfar Yassine" },
          { slug: "kfertai", ar: "كفرتيه", en: "Kfertaï" },
          { slug: "maarab", ar: "معراب", en: "Maarab" },
          { slug: "mayrouba", ar: "ميروبا", en: "Mayrouba" },
          { slug: "mazraet_kfardebiane", ar: "كفردبيان", en: "Mazraet Kfardebiane" },
          { slug: "nahr_el_dahab", ar: "نهر الذهب", en: "Nahr El-Dahab" },
          { slug: "raachine", ar: "رعشين", en: "Raachine" },
          { slug: "rayfoun", ar: "ريفون", en: "Rayfoun" },
          { slug: "tabarja", ar: "طبرجا", en: "Tabarja" },
          { slug: "wata_el_jaouz", ar: "وطى الجوز", en: "Wata-El-Jaouz" },
          { slug: "yahchouche", ar: "يحشوش", en: "Yahchouche" },
          { slug: "zaaitre", ar: "زعيتره", en: "Zaaitré" },
          { slug: "zeitoune", ar: "زيتون", en: "Zeitoune" },
          { slug: "zouk_mikael", ar: "زوق مكايل", en: "Zouk Mikaèl" },
          { slug: "zouk_mousbeh", ar: "زوق مصبح", en: "Zouk Mousbeh" },
        ],
      },
      {
        qada: { slug: "jbeil", ar: "جبيل", en: "Jbeil" },
        villages: [
          { slug: "adonis_et_sannour", ar: "ادونيس", en: "Adonis et Sannour" },
          { slug: "ain_kfah", ar: "عين كفاع", en: "Aïn Kfah" },
          { slug: "ain_el_delbe", ar: "عين الدلبه", en: "Aïn-el-Delbé" },
          { slug: "ain_jraine", ar: "عين جرين", en: "Aïn-Jraïne" },
          { slug: "almate_el_chemaliat", ar: "علمات الشمالية", en: "Almate El-Chemaliat" },
          { slug: "almate_el_jenoubiat", ar: "علمات الجنوبية", en: "Almate El-Jenoubiat" },
          { slug: "amchite", ar: "عمشيت", en: "Amchite" },
          { slug: "bachtlida", ar: "بشتليدا", en: "Bachtlida" },
          { slug: "bazyoune", ar: "بزيون", en: "Bazyoune" },
          { slug: "bchille", ar: "بشللي", en: "Bchillé" },
          { slug: "behdaidate", ar: "بحديدات", en: "Behdaidate" },
          { slug: "beit_habbak", ar: "بيت حباق", en: "Beit Habbak" },
          { slug: "bejje", ar: "بجه", en: "Bejjé" },
          { slug: "blat", ar: "بلاط", en: "Blat" },
          { slug: "chamate", ar: "شامات", en: "Chamate" },
          { slug: "chikhane", ar: "شيخان", en: "Chikhane" },
          { slug: "chmout", ar: "شموت", en: "Chmout" },
          { slug: "edde", ar: "اده", en: "Eddé" },
          { slug: "ehmege", ar: "اهمج", en: "Ehmège" },
          { slug: "el_berbara", ar: "البرباره", en: "El-Berbara" },
          { slug: "el_hsoune", ar: "الحصون", en: "El-Hsoune" },
          { slug: "el_kafr_et_el_harf", ar: "الكفر", en: "El-Kafr et El-Harf" },
          { slug: "el_kharbe", ar: "الخاربه", en: "El-Kharbé" },
          { slug: "el_laklouk", ar: "اللقلوق", en: "El-Laklouk" },
          { slug: "el_mejdel", ar: "المجدل", en: "El-Mejdel" },
          { slug: "el_mghaire", ar: "المغيره", en: "El-Mghaïré" },
          { slug: "el_ramout", ar: "الراموط", en: "El-Ramout" },
          { slug: "el_souane", ar: "الصوانه", en: "El-Souané" },
          { slug: "farhat", ar: "فرحت", en: "Farhat" },
          { slug: "fatre_et_bir_el_hait", ar: "فتري", en: "Fatré et Bir-el-Haït" },
          { slug: "fghal", ar: "فغال", en: "Fghal" },
          { slug: "fidar", ar: "فدار", en: "Fidar" },
          { slug: "frat", ar: "فرات", en: "Frat" },
          { slug: "ghabate", ar: "الغابات", en: "Ghabate" },
          { slug: "ghalboune", ar: "غلبون", en: "Ghalboune" },
          { slug: "gharzouze", ar: "غرزوز", en: "Gharzouze" },
          { slug: "ghorfine", ar: "غرفين", en: "Ghorfine" },
          { slug: "habil", ar: "هابيل", en: "Habil" },
          { slug: "hakel", ar: "حاقل", en: "Hakel" },
          { slug: "halate", ar: "حالات", en: "Halate" },
          { slug: "hbeline", ar: "حبالين", en: "Hbeline" },
          { slug: "hejoula", ar: "حجولا", en: "Hejoula" },
          { slug: "hisrail", ar: "حصرايل", en: "Hisraïl" },
          { slug: "hsarate_et_richkif", ar: "حصارات", en: "Hsarate et Richkif" },
          { slug: "jage", ar: "جاج", en: "Jage" },
          { slug: "janne", ar: "جنه ومار سركيس", en: "Janné" },
          { slug: "jbail", ar: "جبيل", en: "Jbail" },
          { slug: "jeddeyel", ar: "جدايل", en: "Jeddeyel" },
          { slug: "kartaba", ar: "قرطبا الجنوبية", en: "Kartaba" },
          { slug: "kehmez", ar: "قهمز", en: "Kehmez" },
          { slug: "kfar_kedde", ar: "كفر كده", en: "Kfar-Keddé" },
          { slug: "korkraya", ar: "قرقريا", en: "Korkraya" },
          { slug: "lassa", ar: "لاسا", en: "Lassa" },
          { slug: "lehfed", ar: "لحفد", en: "Lehfed" },
          { slug: "maad", ar: "معاد", en: "Maad" },
          { slug: "maifouk", ar: "ميفوق", en: "Maïfouk" },
          { slug: "mazraet_el_siyad", ar: "مزرعة السيد", en: "Mazraet-el-Siyad" },
          { slug: "mechane", ar: "مشان", en: "Mechane" },
          { slug: "nahr_ibrahim", ar: "نهر ابراهيم", en: "Nahr-Ibrahim" },
          { slug: "obeidate", ar: "عبيدات", en: "Obeidate" },
          { slug: "ras_osta", ar: "راس اسطا", en: "Ras-Osta" },
          { slug: "saki_rechmaya", ar: "سقي رشميا", en: "Saki-Rechmaya" },
          { slug: "sakiet_el_kheite", ar: "ساقية الخيط", en: "Sakiet-el-Kheite" },
          { slug: "tartige", ar: "ترتج", en: "Tartige" },
          { slug: "torzaya", ar: "طورزيا", en: "Torzaya" },
          { slug: "yanouh", ar: "يانوح", en: "Yanouh" },
          { slug: "zebdine", ar: "زبدين", en: "Zebdine" },
        ],
      },
    ],
  },
  {
    mohafaza: { slug: "north_lebanon", ar: "شمال لبنان", en: "North Lebanon" },
    qadas: [
      {
        qada: { slug: "tripoli", ar: "طرابلس", en: "Tripoli" },
        villages: [
          { slug: "al_kalmoune", ar: "القلمون", en: "Al-Kalmoune" },
          { slug: "tripoli_al_haddadin", ar: "الحدادين", en: "Tripoli Al Haddadin" },
          { slug: "tripoli_al_hadid", ar: "الحديد", en: "Tripoli Al-Hadid" },
          { slug: "tripoli_al_nouri", ar: "النوري", en: "Tripoli Al-Nouri" },
        ],
      },
      {
        qada: { slug: "koura", ar: "الكورة", en: "Koura" },
        villages: [
          { slug: "aba", ar: "عابا", en: "Aba" },
          { slug: "afsdik", ar: "عفصديق", en: "Afsdik" },
          { slug: "ain_akrine", ar: "عين عكرين", en: "Aïn Akrine" },
          { slug: "amioune", ar: "اميون شرقي, اميون غربي", en: "Amioune" },
          { slug: "badbhoun", ar: "بدبهون", en: "Badbhoun" },
          { slug: "bargoune", ar: "برغون", en: "Bargoune" },
          { slug: "barsa", ar: "برسا", en: "Barsa" },
          { slug: "bdebba", ar: "بدبا", en: "Bdebba" },
          { slug: "bechmezzine", ar: "بشمزين", en: "Bechmezzine" },
          { slug: "beitroumine", ar: "بترومين", en: "Beitroumine" },
          { slug: "bhabbouche", ar: "بحبوش", en: "Bhabbouche" },
          { slug: "bkeftine", ar: "بكفتين", en: "Bkeftine" },
          { slug: "bnehrane", ar: "بنهران", en: "Bnehrane" },
          { slug: "bsarma", ar: "بصرما", en: "Bsarma" },
          { slug: "btaaboura", ar: "بتعبوره", en: "Btaaboura" },
          { slug: "bterram", ar: "بطرام", en: "Bterram" },
          { slug: "btouratige", ar: "بتوراتيج", en: "Btouratige" },
          { slug: "bziza", ar: "بزيزا", en: "Bziza" },
          { slug: "dar_bechtar", ar: "دار بعشتار", en: "Dar Bechtar" },
          { slug: "dar_chmezzine", ar: "دار شمزين", en: "Dar Chmezzine" },
          { slug: "dedde", ar: "دده", en: "Déddé" },
          { slug: "en_nakhle", ar: "النخله", en: "En-Nakhlé" },
          { slug: "enfeh", ar: "انفه", en: "Enfeh" },
          { slug: "fih", ar: "فيع", en: "Fih" },
          { slug: "kaftoune", ar: "كفتون", en: "Kaftoune" },
          { slug: "kelhate", ar: "قلحات", en: "Kelhate" },
          { slug: "kfar_akka", ar: "كفرعقا", en: "Kfar Akka" },
          { slug: "kfar_hatta", ar: "كفرحتى", en: "Kfar Hatta" },
          { slug: "kfar_hazir", ar: "كفر قاهل", en: "Kfar Hazir" },
          { slug: "kfar_kahel", ar: "كفر قاهل", en: "Kfar Kahel" },
          { slug: "kfar_saroun", ar: "كفر صارون", en: "Kfar Saroun" },
          { slug: "kousba", ar: "كوسبا", en: "Kousba" },
          { slug: "metrite", ar: "متريت", en: "Metrite" },
          { slug: "ras_maska", ar: "راس مسقا الجنوبية , راس مسقا الشمالية", en: "Ras Maska" },
          { slug: "rechdebbine", ar: "رشدبين", en: "Rechdebbine" },
          { slug: "zakroune", ar: "زكرون", en: "Zakroune" },
          { slug: "zghorta_el_metaoule", ar: "زغرتا المتاولة", en: "Zghorta el-Métaoulé" },
        ],
      },
      {
        qada: { slug: "zgharta", ar: "زغرتا", en: "Zgharta" },
        villages: [
          { slug: "aintourine", ar: "عينطورين", en: "Aïntourine" },
          { slug: "aito", ar: "ايطو", en: "Aïto" },
          { slug: "al_jdeide", ar: "الجديده", en: "Al-Jdeidé" },
          { slug: "alma", ar: "علما", en: "Alma" },
          { slug: "arde", ar: "ارده", en: "Ardé" },
          { slug: "argesse", ar: "عرجس", en: "Argesse" },
          { slug: "asnoune", ar: "اصنون", en: "Asnoune" },
          { slug: "basloukite", ar: "بسلوقيط", en: "Basloukite" },
          { slug: "bchenine", ar: "بشنين", en: "Bchenine" },
          { slug: "benachee", ar: "بنشعي", en: "Benachée" },
          { slug: "boucite", ar: "بوسيط", en: "Boucite" },
          { slug: "bouhairet_toula", ar: "البحيرة", en: "Bouhairet Toula" },
          { slug: "el_telle", ar: "التل", en: "El-Tellé" },
          { slug: "halane", ar: "حيلان", en: "Halane" },
          { slug: "ial", ar: "ايعال", en: "Iâl" },
          { slug: "karm_sadde", ar: "كرم سده", en: "Karm Saddé" },
          { slug: "kfar_chakna", ar: "كفر شخنا", en: "Kfar Chakna" },
          { slug: "kfar_dalakoss", ar: "كفر دلاقوس", en: "Kfar Dalakoss" },
          { slug: "kfar_haoura", ar: "كفر حورا", en: "Kfar Haoura" },
          { slug: "kfar_hata", ar: "كفرحاتا", en: "Kfar hata" },
          { slug: "kfar_yachite", ar: "كفر ياشيت", en: "Kfar Yachite" },
          { slug: "kfar_zeina", ar: "كفر زينا", en: "Kfar Zeina" },
          { slug: "kfarfou", ar: "كفرفو", en: "Kfarfou" },
          { slug: "kfarsghab", ar: "كفر صغاب", en: "Kfarsghab" },
          { slug: "mazraat_el_teffah", ar: "مزرعة التفاح", en: "Mazraat el Teffah" },
          { slug: "mazraet_hreikess", ar: "حريقص", en: "Mazraet Hreikess" },
          { slug: "meriata", ar: "مرياطه", en: "Mériata" },
          { slug: "miziara", ar: "مزيارة", en: "Miziara" },
          { slug: "rachehine", ar: "رشعين", en: "Rachehine" },
          { slug: "raskifa", ar: "راسكيفا", en: "Raskifa" },
          { slug: "sebhel", ar: "سبعل", en: "Sebhel" },
          { slug: "serhel", ar: "سرعل", en: "Serhel" },
          { slug: "zghorta", ar: "زغرتا حي السيدة الشرقي", en: "Zghorta" },
        ],
      },
      {
        qada: { slug: "batroun", ar: "البترون", en: "Batroun" },
        villages: [
          { slug: "abdilli", ar: "عبدللي", en: "Abdilli" },
          { slug: "abrine", ar: "عبرين", en: "Abrine" },
          { slug: "al_boukaia_et_dahr_abi_yaghi", ar: "ضهر ابو ياغي", en: "Al-Boukaïa et Dahr Abi Yaghi" },
          { slug: "al_hery", ar: "الهري", en: "Al-Hery" },
          { slug: "artiz", ar: "عرتز", en: "Artiz" },
          { slug: "assia", ar: "آسيا", en: "Assia" },
          { slug: "batroune", ar: "البترون", en: "Batroune" },
          { slug: "bchaale", ar: "بشعله", en: "Bchaalé" },
          { slug: "bechtoudar_aoura", ar: "بشتودار", en: "Bechtoudar-Aoura" },
          { slug: "beit_chlale", ar: "بيت شلالا", en: "Beit Chlale" },
          { slug: "bejdarfel", ar: "بجدرفل", en: "Bejdarfel" },
          { slug: "boksmaya", ar: "بقسميا", en: "Boksmaya" },
          { slug: "chabtine", ar: "شبطين", en: "Chabtine" },
          { slug: "chatine", ar: "شاتين", en: "Chatine" },
          { slug: "chekka", ar: "شكا", en: "Chekka" },
          { slug: "dael", ar: "داعل", en: "Dael" },
          { slug: "dar_bella", ar: "دير بلا", en: "Dar Bella" },
          { slug: "deria", ar: "دريا", en: "Deria" },
          { slug: "douk", ar: "دوق", en: "Douk" },
          { slug: "douma", ar: "دوما", en: "Douma" },
          { slug: "ejdabra", ar: "اجدبرا", en: "Ejdabra" },
          { slug: "el_alaly", ar: "العلالي", en: "El-Alaly" },
          { slug: "el_ftahat", ar: "الفتاحات وحربونا", en: "El-Ftahat" },
          { slug: "hadtoune", ar: "حدتون", en: "Hadtoune" },
          { slug: "hamat", ar: "حامات", en: "Hamat" },
          { slug: "hardine", ar: "حردين", en: "Hardine" },
          { slug: "helta", ar: "حلتا", en: "Helta" },
          { slug: "jebla", ar: "جبلا", en: "Jebla" },
          { slug: "jrabta", ar: "جربتا", en: "Jrabta" },
          { slug: "jrane", ar: "جران", en: "Jrane" },
          { slug: "kfar_chleiman", ar: "كفر شليمان", en: "Kfar Chleïman" },
          { slug: "kfar_halda", ar: "كفر حلده", en: "Kfar Halda" },
          { slug: "kfar_hatna", ar: "كفر حتنا", en: "Kfar Hatna" },
          { slug: "kfar_hay", ar: "كفرحي", en: "Kfar Hay" },
          { slug: "kfar_obeida", ar: "كفر عبيدا", en: "Kfar Obeida" },
          { slug: "kfifane", ar: "كفيفان", en: "Kfifane" },
          { slug: "kfour_el_arabi", ar: "كفور العربي", en: "Kfour El-Arabi" },
          { slug: "kour", ar: "كور", en: "Kour" },
          { slug: "mar_mama", ar: "مار ماما", en: "Mar Mama" },
          { slug: "masreh", ar: "مسرح والبقيعة", en: "Masreh" },
          { slug: "mehemrech", ar: "محمرش", en: "Mehemrech" },
          { slug: "mrah_chdid", ar: "مراح شديد ودير شواح", en: "Mrah Chdid" },
          { slug: "mrah_el_hage", ar: "مراح الحاج", en: "Mrah el Hage" },
          { slug: "mrah_el_ziet", ar: "مراح الزيات", en: "Mrah-El-Ziet" },
          { slug: "nahla", ar: "نحلا", en: "Nahla" },
          { slug: "racha", ar: "راشا", en: "Racha" },
          { slug: "rachana", ar: "راشانا", en: "Rachana" },
          { slug: "rachkida", ar: "راشكيده", en: "Rachkida" },
          { slug: "ram", ar: "رام", en: "Ram" },
          { slug: "ras_nahache", ar: "راس نحاش", en: "Ras Nahache" },
          { slug: "salaata", ar: "سلعاتا", en: "Salaata" },
          { slug: "sghar_et_wata_sfarta", ar: "صغار", en: "Sghar et Wata Sfarta" },
          { slug: "smar_jbeil", ar: "سمار جبيل", en: "Smar Jbeil" },
          { slug: "sourate", ar: "صورات", en: "Sourate" },
          { slug: "tannourine_el_tahta", ar: "تنورين التحتا", en: "Tannourine el Tahta" },
          { slug: "tannourine_foka", ar: "تنورين الفوقا", en: "Tannourine Foka" },
          { slug: "tehoum", ar: "تحوم", en: "Tehoum" },
          { slug: "toula", ar: "تولا", en: "Toula" },
          { slug: "wata_houb", ar: "وطى حوب", en: "Wata Houb" },
          { slug: "wejh_el_hajar", ar: "وجه الحجر", en: "Wejh-el-Hajar" },
          { slug: "zane", ar: "زان", en: "Zane" },
        ],
      },
      {
        qada: { slug: "bsharri", ar: "بشرّي", en: "Bsharri" },
        villages: [
          { slug: "abdine", ar: "عبدين", en: "Abdine" },
          { slug: "bane", ar: "بان", en: "Bane" },
          { slug: "bazoune", ar: "بزعون", en: "Bazoune" },
          { slug: "bcharre", ar: "بشري حي السيدة", en: "Bcharré" },
          { slug: "beit_menzer", ar: "بيت منذر", en: "Beit Menzer" },
          { slug: "berhalioun", ar: "برحليون", en: "Berhalioun" },
          { slug: "bikaa_kafra", ar: "بقاعكفرا", en: "Bikaa kafra" },
          { slug: "bkarkacha", ar: "بقرقاشا", en: "Bkarkacha" },
          { slug: "blaouza", ar: "بلوزا", en: "Blaouza" },
          { slug: "brissat", ar: "بريسات", en: "Brissat" },
          { slug: "el_dimane", ar: "الديمان", en: "El-Dimane" },
          { slug: "hadchite", ar: "حدشيت", en: "Hadchite" },
          { slug: "hadeth_el_jebbe", ar: "حدث الجبه", en: "Hadeth-el-Jebbé" },
          { slug: "hasroune", ar: "حصرون", en: "Hasroune" },
          { slug: "knaiouer", ar: "قنيور", en: "Knaiouer" },
          { slug: "knate", ar: "قنات", en: "Knate" },
          { slug: "mazraet_assaf", ar: "مزرعة عساف", en: "Mazraet Assaf" },
          { slug: "mazraet_beni_saab", ar: "مزرعة بني صعب", en: "Mazraet-Beni-Saab" },
          { slug: "tourza", ar: "طورزا", en: "Tourza" },
          { slug: "wadi_kannoubine", ar: "وادي قنوبين", en: "Wadi-kannoubine" },
        ],
      },
      {
        qada: { slug: "miniyeh_danniyeh", ar: "المنية - الضنية", en: "Miniyeh-Danniyeh" },
        villages: [
          { slug: "al_beddaoui", ar: "البداوي", en: "Al-Beddaoui" },
          { slug: "al_sfire", ar: "السفري", en: "Al-Sfiré" },
          { slug: "assoun", ar: "عاصون", en: "Assoun" },
          { slug: "beit_haouik", ar: "بيت حاويك", en: "Beit Haouik" },
          { slug: "beit_el_faks", ar: "بيت الفقس", en: "Beit-El-Faks" },
          { slug: "bkaa_safrine", ar: "بقاع صفرين", en: "Bkaa Safrine" },
          { slug: "borge_el_yahoudie", ar: "برج اليهودية", en: "Borge-El-Yahoudié" },
          { slug: "btermaz", ar: "بطرماز", en: "Btermaz" },
          { slug: "debaael", ar: "دبعال", en: "Debaael" },
          { slug: "deir_nebouh", ar: "دير نبوح", en: "Deir Nebouh" },
          { slug: "deir_omar", ar: "دير عمار", en: "Deir Omar" },
          { slug: "el_hazmieh", ar: "الحازميه", en: "El-Hazmieh" },
          { slug: "haql_el_aazime", ar: "حقل العزيمه", en: "Haql el Aazimé" },
          { slug: "hawara", ar: "حوارة", en: "Hawara" },
          { slug: "izal", ar: "ايزال", en: "Izal" },
          { slug: "kahf_el_malloul", ar: "كهف الملول", en: "Kahf-El-Malloul" },
          { slug: "karseita", ar: "قرصيتا", en: "Karseita" },
          { slug: "kfar_chlane", ar: "كفر شلان", en: "Kfar Chlane" },
          { slug: "kfar_habou", ar: "كفر حبو", en: "Kfar Habou" },
          { slug: "markabta", ar: "مركبتا", en: "Markabta" },
          { slug: "mazraet_el_kreine", ar: "مزرعة القرين", en: "Mazraet-El-Kreine" },
          { slug: "mrah_el_sreige", ar: "مراح السريج", en: "Mrah-el-Sreige" },
          { slug: "nabi_youcheaa", ar: "النبي يوشع", en: "Nabi Youcheaa" },
          { slug: "sir", ar: "سير", en: "Sir" },
          { slug: "tarane", ar: "طاران", en: "Tarane" },
          { slug: "zaghrteghrine", ar: "زغرتغرين", en: "Zaghrteghrine" },
        ],
      },
    ],
  },
  {
    mohafaza: { slug: "south_lebanon", ar: "جنوب لبنان", en: "South Lebanon" },
    qadas: [
      {
        qada: { slug: "sidon", ar: "صيدا", en: "Sidon" },
        villages: [
          { slug: "abra", ar: "عبرا", en: "Abra" },
          { slug: "adloun", ar: "عدلون", en: "Adloun" },
          { slug: "aktanite", ar: "عقتنيت", en: "Aktanite" },
          { slug: "ankoune", ar: "عنقون", en: "Ankoune" },
          { slug: "ansariye", ar: "انصاريه", en: "Ansariyé" },
          { slug: "arab_el_jal", ar: "عرب الجل", en: "Arab-el-Jal" },
          { slug: "arke", ar: "اركي", en: "Arké" },
          { slug: "arzey", ar: "ارزي", en: "Arzey" },
          { slug: "babliye", ar: "البابلية", en: "Babliyé" },
          { slug: "berti", ar: "برتي", en: "Berti" },
          { slug: "bnaafoul", ar: "بنعفول", en: "Bnaafoul" },
          { slug: "bqosta", ar: "بقسطه", en: "Bqosta" },
          { slug: "bramiat", ar: "البرامية", en: "Bramiat" },
          { slug: "el_husseiniye", ar: "الحسينية", en: "El-Husseiniyé" },
          { slug: "el_kharayeb", ar: "الخرايب", en: "El-Kharayeb" },
          { slug: "el_merwaniye", ar: "المروانية", en: "El-Merwaniyé" },
          { slug: "el_zrariye", ar: "الزرارية", en: "El-Zrariyé" },
          { slug: "ghassaniye", ar: "غسانية", en: "Ghassaniyé" },
          { slug: "ghazyat", ar: "الغازية", en: "Ghazyat" },
          { slug: "haret_saida", ar: "الحارة", en: "Haret Saïda" },
          { slug: "helaliat", ar: "الهلالية", en: "Helaliat" },
          { slug: "kanarite", ar: "قناريت", en: "Kanarite" },
          { slug: "kfar_melki", ar: "كفرملكي", en: "Kfar Melki" },
          { slug: "kfar_bite", ar: "كفربيت", en: "Kfar-Bite" },
          { slug: "kfar_challal", ar: "كفرشلال", en: "Kfar-Challal" },
          { slug: "khartoum", ar: "خرطوم", en: "Khartoum" },
          { slug: "khazize", ar: "خزيز", en: "Khazize" },
          { slug: "kraye", ar: "القرية", en: "Krayé" },
          { slug: "maghdouche", ar: "مغدوشه", en: "Maghdouché" },
          { slug: "majdalioun", ar: "مجدليون", en: "Majdalioun" },
          { slug: "saida_dekerman", ar: "صيدا حي الدكرمان", en: "Saïda Dekerman" },
          { slug: "saida_ville", ar: "صيدا البلدة", en: "Saïda Ville" },
          { slug: "saida_wastani", ar: "صيدا حي الوسطاني", en: "Saïda Wastani" },
          { slug: "salhiat", ar: "الصالحية", en: "Salhiat" },
          { slug: "sarafend", ar: "الصرفند", en: "Sarafend" },
          { slug: "sari", ar: "ساري", en: "Sari" },
          { slug: "tanbourite", ar: "طنبوريت", en: "Tanbourite" },
          { slug: "teffehta", ar: "تفاحتا", en: "Teffehta" },
          { slug: "zaghdraya", ar: "زغدرايا", en: "Zaghdraya" },
          { slug: "zeita", ar: "زيتا", en: "Zeita" },
        ],
      },
      {
        qada: { slug: "tyre", ar: "صور", en: "Tyre" },
        villages: [
          { slug: "abbassyat", ar: "عباسية", en: "Abbassyat" },
          { slug: "ain_abou_abdallah", ar: "عين ابو عبدالله", en: "Aïn Abou Abdallah" },
          { slug: "ain_baal", ar: "عين بعال", en: "Aïn Baal" },
          { slug: "aitite", ar: "عيتيت", en: "Aïtite" },
          { slug: "alma_chaab", ar: "علما الشعب", en: "Alma Chaab" },
          { slug: "arzoune", ar: "ارزون", en: "Arzoune" },
          { slug: "bafliye", ar: "بافليه", en: "Bafliyé" },
          { slug: "batouliyat", ar: "باتولية", en: "Batouliyat" },
          { slug: "beiriche", ar: "باريش", en: "Beiriche" },
          { slug: "bidias", ar: "بدياس", en: "Bidias" },
          { slug: "bordje_rahhal", ar: "برج رحال", en: "Bordje Rahhal" },
          { slug: "borge_el_chemali", ar: "برج الشمالي", en: "Borge El-Chémali" },
          { slug: "boustane", ar: "البستان", en: "Boustane" },
          { slug: "chehour", ar: "شحور", en: "Chehour" },
          { slug: "cheietiye", ar: "الشعيتية", en: "Cheïetiyé" },
          { slug: "chihine", ar: "شيحين", en: "Chihine" },
          { slug: "deir_amess", ar: "دير عامص", en: "Deir Amess" },
          { slug: "deir_kanoun_el_nahr", ar: "دير قانون النهر", en: "Deir Kanoun El-Nahr" },
          { slug: "deir_kanoun_ras_el_ain", ar: "دير قانون راس العين", en: "Deir Kanoun Ras El Aïn" },
          { slug: "deir_kifa", ar: "دير كيفا", en: "Deir Kifa" },
          { slug: "derdaghaya", ar: "دردغيا", en: "Derdaghaya" },
          { slug: "el_jbine", ar: "الجبين", en: "El Jbine" },
          { slug: "el_biyad", ar: "البياض", en: "El-Biyad" },
          { slug: "el_henniye", ar: "الحنية", en: "El-Henniyé" },
          { slug: "el_kleile", ar: "قليله", en: "El-Kleilé" },
          { slug: "el_mansouri", ar: "المنصوري", en: "El-Mansouri" },
          { slug: "hanawe", ar: "حناويه", en: "Hanawé" },
          { slug: "hmaire", ar: "حميره", en: "Hmairé" },
          { slug: "izzie", ar: "عزه", en: "Izzié" },
          { slug: "jebel_el_batm", ar: "جبال البطم", en: "Jebel-El-Batm" },
          { slug: "jennata", ar: "جنتا", en: "Jennata" },
          { slug: "jouaya", ar: "جويا", en: "Jouaya" },
          { slug: "kana", ar: "قانا", en: "Kana" },
          { slug: "maarake", ar: "معركة", en: "Mâaraké" },
          { slug: "mahroub", ar: "معروب", en: "Mahroub" },
          { slug: "majdalzoun", ar: "مجدلزون", en: "Majdalzoun" },
          { slug: "marouhine", ar: "مروحين", en: "Marouhine" },
          { slug: "mazraat_mechref", ar: "مزرعة مشرف", en: "Mazraat Mechref" },
          { slug: "mjadel", ar: "مجادل", en: "Mjadel" },
          { slug: "nakoura", ar: "الناقورة", en: "Nakoura" },
          { slug: "neffahiye", ar: "نفاخيه", en: "Neffahiyé" },
          { slug: "ouadi_djilou", ar: "وادي جيلو", en: "Ouadi Djilou" },
          { slug: "recheknaniyeh", ar: "رشكنانيه", en: "Recheknaniyeh" },
          { slug: "remadiyeh", ar: "الرماديه", en: "Remadiyeh" },
          { slug: "saddikine", ar: "صديقين", en: "Saddikine" },
          { slug: "sour_tyr", ar: "صور", en: "Sour (Tyr)" },
          { slug: "srifa", ar: "صريفا", en: "Srifa" },
          { slug: "tair_harf", ar: "طير حرفا", en: "Tair Harf" },
          { slug: "tair_dabba", ar: "طير دبا", en: "Taïr-Dabba" },
          { slug: "touaire", ar: "طير فلسيه", en: "Touaire" },
          { slug: "toura", ar: "طورا", en: "Toura" },
          { slug: "yarine", ar: "يارين", en: "Yarine" },
          { slug: "zebkine", ar: "زبقين", en: "Zebkine" },
        ],
      },
      {
        qada: { slug: "jezzine", ar: "جزين", en: "Jezzine" },
        villages: [
          { slug: "aichiye", ar: "العيشية", en: "Aïchiyé" },
          { slug: "ain_el_mir", ar: "عين المير", en: "Aïn el-Mir" },
          { slug: "anane", ar: "انان", en: "Anane" },
          { slug: "aramte", ar: "الرامة", en: "Aramté" },
          { slug: "ariya", ar: "صفارية", en: "Ariya" },
          { slug: "azour", ar: "عازور", en: "Azour" },
          { slug: "baissour", ar: "بيصور", en: "Baissour" },
          { slug: "benwati", ar: "بنواتي", en: "Benwati" },
          { slug: "bhanine", ar: "بحنين", en: "Bhanine" },
          { slug: "bisri", ar: "بسري", en: "Bisri" },
          { slug: "bkessine", ar: "بكاسين", en: "Bkessine" },
          { slug: "bouslaya", ar: "بصليا", en: "Bouslaya" },
          { slug: "bteddine_el_lekche", ar: "بتدين اللقش", en: "Bteddine El-Lekche" },
          { slug: "chawalik", ar: "شواليق", en: "Chawalik" },
          { slug: "djezzine", ar: "جزين", en: "Djezzine" },
          { slug: "el_ghabbatieh", ar: "الغباطيه", en: "El-Ghabbatieh" },
          { slug: "el_harf", ar: "الحرف", en: "El-Harf" },
          { slug: "el_homsiye", ar: "الحمصية", en: "El-Homsiyé" },
          { slug: "el_jarmak", ar: "الجرمق", en: "El-Jarmak" },
          { slug: "el_louaize", ar: "اللويزه", en: "El-Louaizé" },
          { slug: "el_maknouniye", ar: "المكنونيه", en: "El-Maknouniyé" },
          { slug: "el_mharbiye", ar: "المحاربيه", en: "El-Mharbiyé" },
          { slug: "el_midan", ar: "الميدان", en: "El-Midan" },
          { slug: "el_remmane", ar: "عين الرمانة", en: "El-Remmané" },
          { slug: "el_zeghrine", ar: "الزغرين", en: "El-Zeghrine" },
          { slug: "haitoule", ar: "حيتوله - وادي الليمون", en: "Haitoulé" },
          { slug: "haitoura", ar: "حيطوره", en: "Haïtoura" },
          { slug: "hassaniye", ar: "الحسانيه", en: "Hassaniyé" },
          { slug: "jensnaya", ar: "جنسنايا", en: "Jensnaya" },
          { slug: "kafr_falouce", ar: "كفرفالوس", en: "Kafr-Falouce" },
          { slug: "kafr_jarra", ar: "كفر جره", en: "Kafr-Jarra" },
          { slug: "kaitoule", ar: "قيتولي", en: "Kaïtoulé" },
          { slug: "karkha", ar: "كرخا", en: "Karkha" },
          { slug: "katrani", ar: "القطراني", en: "Katrani" },
          { slug: "kattine", ar: "قطين وحيداب", en: "Kattine" },
          { slug: "kefer_houne", ar: "كفرحونه", en: "Kefer-Houné" },
          { slug: "lebaa", ar: "لبعا", en: "Lebaa" },
          { slug: "machmouche", ar: "مشموشه", en: "Machmouché" },
          { slug: "mazraat_el_mathane", ar: "مزرعة المطحنة", en: "Mazraat el-Mathané" },
          { slug: "mjaidel", ar: "مجيدل", en: "Mjaïdel" },
          { slug: "mlikh", ar: "مليخ", en: "Mlikh" },
          { slug: "mrah_el_hbasse", ar: "مراح الحباس", en: "Mrah-el-Hbasse" },
          { slug: "rimate", ar: "ريمات وشقاديف", en: "Rimate" },
          { slug: "roum", ar: "روم", en: "Roum" },
          { slug: "sabbah", ar: "صباح", en: "Sabbah" },
          { slug: "saidoune", ar: "صيدون", en: "Saïdoune" },
          { slug: "sniye", ar: "سنيه", en: "Sniyé" },
          { slug: "soujoud", ar: "سجد", en: "Soujoud" },
          { slug: "srayri", ar: "السريره", en: "Srayri" },
          { slug: "taid", ar: "تعيد", en: "Taïd" },
          { slug: "wadi_baankoudine", ar: "وادي بعنقودين", en: "Wadi Baankoudine" },
          { slug: "wadi_djezzine", ar: "وادي جزين", en: "Wadi Djezzine" },
          { slug: "zhalta", ar: "زحلته", en: "Zhalta" },
        ],
      },
    ],
  },
  {
    mohafaza: { slug: "nabatieh", ar: "النبطية", en: "Nabatieh" },
    qadas: [
      {
        qada: { slug: "nabatieh", ar: "النبطية", en: "Nabatieh" },
        villages: [
          { slug: "adchite", ar: "عدشيت", en: "Adchite" },
          { slug: "ain_boussouar", ar: "عين بوسوار", en: "Aïn-Boussouar" },
          { slug: "ain_kana", ar: "عين قانا", en: "Aïn-Kana" },
          { slug: "ansar", ar: "انصار", en: "Ansar" },
          { slug: "arab_salim", ar: "عرب صاليم", en: "Arab Salim" },
          { slug: "arnoune", ar: "ارنون", en: "Arnoune" },
          { slug: "braikeh", ar: "بريقع", en: "Braikeh" },
          { slug: "choukine", ar: "شوكين", en: "Choukine" },
          { slug: "deir_el_zehrani", ar: "دير الزهراني", en: "Deir El-Zehrani" },
          { slug: "douair", ar: "الدوير", en: "Douair" },
          { slug: "habbouche", ar: "حبوش", en: "Habbouche" },
          { slug: "harouf", ar: "حاروف", en: "Harouf" },
          { slug: "houmine_el_tahta", ar: "حومين التحتا", en: "Houmine El-Tahta" },
          { slug: "houmine_el_faouka", ar: "حومين الفوقا", en: "Houmine-el-Faouka" },
          { slug: "jarjouh", ar: "جرجوع", en: "Jarjouh" },
          { slug: "jernaya", ar: "جرنايا", en: "Jernaya" },
          { slug: "jobchite", ar: "جبشيت", en: "Jobchite" },
          { slug: "kefer_sir", ar: "كفرصير", en: "Kefer Sir" },
          { slug: "kfar_remmane", ar: "كفررمان", en: "Kfar Remmane" },
          { slug: "kfar_tebnite", ar: "كفر تبنيت", en: "Kfar Tebnite" },
          { slug: "kfarfila", ar: "كفرفيلا", en: "Kfarfila" },
          { slug: "maifadoune", ar: "ميفدون", en: "Maifadoune" },
          { slug: "mazraet_sinai", ar: "سيني", en: "Mazraet Sinai" },
          { slug: "nabatiye_el_faouka", ar: "النبطية الفوقا", en: "Nabatiyé El-Faouka" },
          { slug: "nabatiye_el_tahta", ar: "النبطية التحتا حي البياض , النبطية التحتا حي السراي , النبطية التحتا حي المسيحيين , النبطية التحتا حي الميدان", en: "Nabatiyé El-Tahta" },
          { slug: "nmeriye", ar: "النميريه", en: "Nmériyé" },
          { slug: "roumine", ar: "رومين", en: "Roumine" },
          { slug: "sarba", ar: "صربا", en: "Sarba" },
          { slug: "sir_el_gharbiye", ar: "صير الغربية", en: "Sir El-Gharbiyé" },
          { slug: "toule", ar: "تول", en: "Toule" },
          { slug: "zaoutar_el_charkiye", ar: "زوطر الشرقية", en: "Zaoutar El-Charkiyé" },
          { slug: "zaoutar_el_gharbiye", ar: "زوطر الغربية", en: "Zaoutar El-Gharbiyé" },
          { slug: "zefta", ar: "زفتا", en: "Zefta" },
        ],
      },
      {
        qada: { slug: "hasbaya", ar: "حاصبيا", en: "Hasbaya" },
        villages: [
          { slug: "abou_kamha", ar: "ابو قمحه", en: "Abou Kamha" },
          { slug: "ain_jarfa", ar: "عين جرفا", en: "Aïn Jarfa" },
          { slug: "ain_kinia", ar: "عين قنيا", en: "Aïn Kinia" },
          { slug: "burghoz", ar: "برغز", en: "Burghoz" },
          { slug: "chabaaa", ar: "شبعا شرقي , شبعا غربي", en: "Chabaaa" },
          { slug: "chebaa_farms", ar: "مزارع شبعا", en: "Chebaa Farms" },
          { slug: "el_mery", ar: "الماري", en: "El- Mery" },
          { slug: "el_fraidice", ar: "الفريديس", en: "El-Fraïdice" },
          { slug: "el_kfeir", ar: "الكفير", en: "El-Kfeir" },
          { slug: "el_majidiye", ar: "المجيديه", en: "El-Majidiyé" },
          { slug: "hasbaya", ar: "حاصبيا حي السراي , حاصبيا حي العين , حاصبيا حي الفوقاني , حاصبيا حي صفيفة", en: "Hasbaya" },
          { slug: "kfar_hamame", ar: "كفر حمام", en: "Kfar Hamame" },
          { slug: "marj_ez_zouhour_haouch_el_qinnaabe", ar: "مرج الزهور", en: "Marj Ez-Zouhour (Haouch El-Qinnaabé)" },
          { slug: "mimas", ar: "ميماس", en: "Mimas" },
          { slug: "rachaya_el_fokhar", ar: "راشيا الفخار", en: "Rachaya El-Fokhar" },
        ],
      },
      {
        qada: { slug: "marjeyoun", ar: "مرجعيون", en: "Marjeyoun" },
        villages: [
          { slug: "ain_aarab", ar: "عين عرب", en: "Ain Aarab" },
          { slug: "al_taibe", ar: "الطيبه", en: "Al-Taïbé" },
          { slug: "bani_haiyane", ar: "بني حيان", en: "Bani Haiyane" },
          { slug: "blida", ar: "بليدا", en: "Blida" },
          { slug: "deir_mimas", ar: "دير ميماس", en: "Deir Mimas" },
          { slug: "deir_seriane", ar: "دير سريان", en: "Deir Sériane" },
          { slug: "dibbine", ar: "دبين", en: "Dibbine" },
          { slug: "ebel_el_saki", ar: "ابل السقي", en: "Ebel-El-Saki" },
          { slug: "el_kherbeh", ar: "الخربة", en: "El-Kherbeh" },
          { slug: "el_khiam", ar: "الخيام جنوبي , الخيام شرقي , الخيام شمالي , الخيام غربي", en: "EL-Khiam" },
          { slug: "houla", ar: "حولا", en: "Houla" },
          { slug: "kabrikha", ar: "قبريخا", en: "Kabrikha" },
          { slug: "kantara", ar: "قنطره", en: "Kantara" },
          { slug: "kfarkala", ar: "كفركلا", en: "Kfarkala" },
          { slug: "majdel_selm", ar: "مجدل سلم", en: "Majdel Selm" },
          { slug: "markaba", ar: "مركبا", en: "Markaba" },
          { slug: "meis_el_jabal", ar: "ميس الجبل جنوبي", en: "Meis El-Jabal" },
          { slug: "merjayoun", ar: "مرجعيون", en: "Merjayoun" },
          { slug: "mhaibib", ar: "محيبيب", en: "Mhaïbib" },
          { slug: "souane", ar: "صوانه", en: "Souané" },
          { slug: "talloussa", ar: "طلوسه", en: "Talloussa" },
          { slug: "touline", ar: "تولين", en: "Touline" },
        ],
      },
      {
        qada: { slug: "bint_jbeil", ar: "بنت جبيل", en: "Bint Jbeil" },
        villages: [
          { slug: "ain_ebel", ar: "عين ابل حي الدير,عين ابل حي العين,عين ابل حي الكنيسة", en: "Aïn-Ebel" },
          { slug: "aita_el_chaab", ar: "عيتا الشعب", en: "Aïta-el-Chaab" },
          { slug: "aitaroun", ar: "عيترون", en: "Aïtaroun" },
          { slug: "baraachite", ar: "برعشيت", en: "Baraachite" },
          { slug: "beit_lif", ar: "بيت ليف", en: "Beit Lif" },
          { slug: "beit_yahoune", ar: "بيت ياحون", en: "Beit Yahoune" },
          { slug: "bint_jbail", ar: "بنت جبيل حي البركه,بنت جبيل حي الجامع,بنت جبيل حي الحسينية,بنت جبيل حي الحواره,بنت جبيل حي عين الصغيرة", en: "Bint Jbail" },
          { slug: "borge_kalaouiye", ar: "برج قلاويه", en: "Borge Kalaouiyé" },
          { slug: "chakra", ar: "شقرا", en: "Chakra" },
          { slug: "debel", ar: "دبل", en: "Debel" },
          { slug: "deir_ntar", ar: "دير انطار", en: "Deir Ntar" },
          { slug: "el_kouzah", ar: "قوزح", en: "El-Kouzah" },
          { slug: "el_tairi", ar: "الطيري", en: "El-Taïri" },
          { slug: "froune", ar: "فرون", en: "Froune" },
          { slug: "ghandouriye", ar: "غندورية", en: "Ghandouriyé" },
          { slug: "hanine", ar: "حانين", en: "Hanine" },
          { slug: "harisse", ar: "حاريص", en: "Harisse" },
          { slug: "jmeijme", ar: "جميجمه", en: "Jmeijmé" },
          { slug: "kafra", ar: "كفره", en: "Kafra" },
          { slug: "kalaouiye", ar: "قلاويه", en: "Kalaouiyé" },
          { slug: "kfardounine", ar: "كفردونين", en: "Kfardounine" },
          { slug: "kherbet_salem", ar: "خربة سلم", en: "Kherbet Salem" },
          { slug: "kounine", ar: "كونين", en: "Kounine" },
          { slug: "maroune_el_ras", ar: "مارون الراس", en: "Maroune-el-Ras" },
          { slug: "rachafe", ar: "رشاف", en: "Rachafe" },
          { slug: "ramie", ar: "راميه", en: "Ramié" },
          { slug: "rmeiche", ar: "رميش", en: "Rmeiche" },
          { slug: "safad_el_battikh", ar: "صفد البطيخ", en: "Safad-el-Battikh" },
          { slug: "sarbine", ar: "صربين", en: "Sarbine" },
          { slug: "soultaniye", ar: "السلطانيه", en: "Soultaniyé" },
          { slug: "tibnine", ar: "تبنين حي التحتاني,تبنين حي الفوقاني,تبنين حي الكاثوليك,تبنين حي آل بري", en: "Tibnine" },
          { slug: "yaroune", ar: "يارون", en: "Yaroune" },
          { slug: "yater", ar: "ياطر", en: "Yater" },
        ],
      },
    ],
  },
  {
    mohafaza: { slug: "bekaa", ar: "البقاع", en: "Bekaa" },
    qadas: [
      {
        qada: { slug: "zahle", ar: "زحلة", en: "Zahlé" },
        villages: [
          { slug: "ablah", ar: "ابلح", en: "Ablah" },
          { slug: "ain_kfar_zabed", ar: "عين كفرزبد", en: "Aïn Kfar Zabed" },
          { slug: "al_ali_nahri", ar: "علي النهري", en: "Al-Ali-Nahri" },
          { slug: "al_mazraa", ar: "المزرعة", en: "Al-Mazraa" },
          { slug: "al_nabi_aila", ar: "نبي ايلا", en: "Al-Nabi Aïla" },
          { slug: "al_nasriye", ar: "ناصريه", en: "Al-Nasriyé" },
          { slug: "anjar", ar: "مجدل عنجر", en: "Anjar" },
          { slug: "bar_elias", ar: "بر الياس", en: "Bar-Elias" },
          { slug: "bouerije", ar: "بوارج", en: "Bouerije" },
          { slug: "chtaura", ar: "شتوره", en: "Chtaura" },
          { slug: "dair_el_ghazel", ar: "دير الغزال", en: "Dair-el-Ghazel" },
          { slug: "delhamie", ar: "دلهميه", en: "Delhamié" },
          { slug: "fourzol", ar: "الفرزل التحتا", en: "Fourzol" },
          { slug: "haouche_hala", ar: "حوش حالا", en: "Haouche Hala" },
          { slug: "haouche_el_ghanam", ar: "حوش الغنم", en: "Haouche-el-Ghanam" },
          { slug: "hizzerta", ar: "حزرتا", en: "Hizzerta" },
          { slug: "jditah", ar: "جديتا", en: "Jditah" },
          { slug: "kaa_el_rime", ar: "قاع الريم", en: "Kaa-el-Rime" },
          { slug: "kfar_zabed", ar: "كفرزبد", en: "Kfar Zabed" },
          { slug: "koussaya", ar: "قوسايا", en: "Koussaya" },
          { slug: "makse", ar: "مكسه", en: "Maksé" },
          { slug: "massa", ar: "ماسا", en: "Massa" },
          { slug: "mreijat", ar: "مريجات", en: "Mreijat" },
          { slug: "niha", ar: "نيحا", en: "Niha" },
          { slug: "rait", ar: "رعيت", en: "Rait" },
          { slug: "rayak", ar: "رياق", en: "Rayak" },
          { slug: "said_neil", ar: "سعدنايل", en: "Saïd Neil" },
          { slug: "talabaya", ar: "تعلبايا", en: "Talabaya" },
          { slug: "tanail", ar: "تعنايل", en: "Tanaïl" },
          { slug: "terbol", ar: "تربل", en: "Terbol" },
          { slug: "touaite", ar: "تويته", en: "Touaité" },
          { slug: "wadi_el_dalam", ar: "وادي الدلم", en: "Wadi-el-Dalam" },
          { slug: "zahle_barbara", ar: "زحلة البرباره", en: "Zahlé Barbara" },
          { slug: "zahle_haouche_al_oumara", ar: "زحلة حوش الامراء", en: "Zahlé Haouche Al-Oumara" },
          { slug: "zahle_haouche_al_zaraane", ar: "زحلة حوش الزراعنه", en: "Zahlé Haouche Al-Zaraané" },
          { slug: "zahle_mar_antonios", ar: "زحلة مار انطونيوس", en: "Zahlé Mar Antonios" },
          { slug: "zahle_mar_elias", ar: "زحلة مار الياس", en: "Zahlé Mar Elias" },
          { slug: "zahle_midan", ar: "زحلة الميدان الشرقي", en: "Zahlé Midan" },
          { slug: "zahle_saidet_al_najda", ar: "زحلة سيدة النجاة", en: "Zahlé Saidet Al-Najda" },
        ],
      },
      {
        qada: { slug: "western_bekaa", ar: "البقاع الغربي", en: "Western Bekaa" },
        villages: [
          { slug: "ain_el_tine", ar: "عين التينة", en: "Aïn-el-Tiné" },
          { slug: "ain_zebde", ar: "عين زبده", en: "Aïn-Zebdé" },
          { slug: "aitanit", ar: "عيتنيت", en: "Aïtanit" },
          { slug: "al_marje", ar: "المرج", en: "Al-Marje" },
          { slug: "al_sawire", ar: "الصويري", en: "Al-Sawiré" },
          { slug: "al_wakf", ar: "الوقف", en: "Al-Wakf" },
          { slug: "ana", ar: "عانا", en: "Ana" },
          { slug: "baaloul", ar: "بعلول", en: "Baaloul" },
          { slug: "bab_mareh", ar: "باب مارع", en: "Bab Mareh" },
          { slug: "dakoue", ar: "الدكوه", en: "Dakoué" },
          { slug: "el_karaoun", ar: "القرعون", en: "El-Karaoun" },
          { slug: "ghazze", ar: "غزه", en: "Ghazzé" },
          { slug: "hamara", ar: "المنارة", en: "Hamara" },
          { slug: "haouche_el_harime", ar: "حوش الحريمه", en: "Haouche-el-Harimé" },
          { slug: "jib_jenine", ar: "جب جنين", en: "Jib Jénine" },
          { slug: "kamed_el_lauze", ar: "كامد اللوز", en: "Kamed-el-Lauze" },
          { slug: "kefraya", ar: "كفريا", en: "Kefraya" },
          { slug: "kelia", ar: "قليا", en: "Kélia" },
          { slug: "kherbet_kanafar", ar: "خربة قنافار", en: "Kherbet Kanafar" },
          { slug: "lala", ar: "لالا", en: "Lala" },
          { slug: "lebbaya", ar: "لبايا", en: "Lebbaya" },
          { slug: "loucia", ar: "لوسيا", en: "Loucia" },
          { slug: "maidoune", ar: "ميدون", en: "Maïdoune" },
          { slug: "mansoura", ar: "المنصوره", en: "Mansoura" },
          { slug: "saghbine", ar: "صغبين", en: "Saghbine" },
          { slug: "sohmor", ar: "سحمر", en: "Sohmor" },
          { slug: "soltan_yacoub", ar: "السلطان يعقوب التحتا", en: "Soltan-Yacoub" },
          { slug: "tal_zenoub", ar: "تل ذنوب", en: "Tal Zenoub" },
          { slug: "yohmor", ar: "يحمر", en: "Yohmor" },
          { slug: "zellaya", ar: "زلايا", en: "Zellaya" },
        ],
      },
      {
        qada: { slug: "rashaya", ar: "راشيا", en: "Rashaya" },
        villages: [
          { slug: "ain_aata", ar: "عين عطا", en: "Aïn Aata" },
          { slug: "ain_arab", ar: "عين حرشا", en: "Aïn Arab" },
          { slug: "aita_el_fokhar", ar: "عيتا الفخار", en: "Aïta El-Fokhar" },
          { slug: "akabe", ar: "العقبة", en: "Akabé" },
          { slug: "bakka", ar: "بكا", en: "Bakka" },
          { slug: "bakkifa", ar: "بكيفا", en: "Bakkifa" },
          { slug: "beit_lahia", ar: "بيت لهيا", en: "Beit Lahia" },
          { slug: "dahr_el_ahmar", ar: "ضهر الاحمر", en: "Dahr El-Ahmar" },
          { slug: "el_rafide", ar: "الرفيد", en: "El-RafidE" },
          { slug: "heloua", ar: "حلوه", en: "Héloua" },
          { slug: "kaoukaba", ar: "كوكبا", en: "Kaoukaba" },
          { slug: "kfar_mechke", ar: "كفرمشكي", en: "Kfar Mechké" },
          { slug: "kherbet_rouha", ar: "خربة روحا", en: "Kherbet Rouha" },
          { slug: "majdel_balhice", ar: "مجدل بلهيص", en: "Majdel Balhice" },
          { slug: "mazraet_el_selasata", ar: "سلساتا", en: "Mazraet el-Selasata" },
          { slug: "mdoukha", ar: "مدوخا", en: "Mdoukha" },
          { slug: "tannoura", ar: "تنوره", en: "Tannoura" },
          { slug: "yanta", ar: "ينطا", en: "Yanta" },
        ],
      },
    ],
  },
  {
    mohafaza: { slug: "baalbek_hermel", ar: "بعلبك - الهرمل", en: "Baalbek-Hermel" },
    qadas: [
      {
        qada: { slug: "baalbek", ar: "بعلبك", en: "Baalbek" },
        villages: [
          { slug: "addous", ar: "وادي العس", en: "Addous" },
          { slug: "ain_bourday", ar: "عين بورضاي", en: "Aïn Bourday" },
          { slug: "ainata", ar: "عيناتا", en: "Aïnata" },
          { slug: "al_labouat", ar: "اللبوة", en: "Al-Labouat" },
          { slug: "al_nabi_chite", ar: "النبي شيت حي الجامع", en: "Al-Nabi Chite" },
          { slug: "al_nabi_osman", ar: "النبي عثمان", en: "Al-Nabi Osman" },
          { slug: "arsale", ar: "عرسال جنوبي , عرسال شرقي , عرسال شمالي , عين السوداء", en: "Arsale" },
          { slug: "baalbek", ar: "راس بعلبك", en: "Baalbek" },
          { slug: "bachwat", ar: "بشوات", en: "Bachwat" },
          { slug: "bait_chama", ar: "بيت شاما", en: "Bait Chama" },
          { slug: "barka", ar: "برقه", en: "Barka" },
          { slug: "bednayel", ar: "بدنايل", en: "Bednayel" },
          { slug: "bouday", ar: "بوداي", en: "Bouday" },
          { slug: "brital", ar: "بريتال اليونسية ,بريتال حي التين ,بريتال شرقي ,بريتال شميس ,بريتال شميس غربي ,بريتال عين البنيه ,بريتال عين الجوز ,بريتال غربي", en: "Brital" },
          { slug: "btedy", ar: "بتدعي", en: "Btédy" },
          { slug: "chaat", ar: "شعت حي الجامع", en: "Chaat" },
          { slug: "chemistar", ar: "شمسطار الجنوبي ,شمسطار الشرقي, شمسطار الشمالي, شمسطار الغربي", en: "Chemistar" },
          { slug: "chlifa", ar: "شليفا", en: "Chlifa" },
          { slug: "couvent_st_maron", ar: "حي الست", en: "Couvent St Maron" },
          { slug: "dair_el_ahmar", ar: "دير الاحمر", en: "Dair El-Ahmar" },
          { slug: "douress", ar: "دورس حي البير , دورس حي السيدة , دورس حي الشحاديه", en: "Douress" },
          { slug: "el_ram", ar: "الرام", en: "El-Ram" },
          { slug: "ham", ar: "حام", en: "Ham" },
          { slug: "haouch_el_nabi", ar: "حوش النبي", en: "Haouch el Nabi" },
          { slug: "haouche_al_sonaid", ar: "حوش سنيد", en: "Haouche Al-Sonaid" },
          { slug: "haouche_barada", ar: "حوش بردى", en: "Haouche Barada" },
          { slug: "haouche_el_dahab", ar: "حوش الذهب", en: "Haouche El-Dahab" },
          { slug: "haouche_el_rafika", ar: "حوش الرافقه", en: "Haouche el-Rafika" },
          { slug: "haouche_el_tal_safyat", ar: "حوش تل صفيه", en: "Haouche El-Tal Safyat" },
          { slug: "harbta", ar: "حربتا", en: "Harbta" },
          { slug: "hizzine", ar: "حزين", en: "Hizzine" },
          { slug: "hourtala", ar: "حور تعلا , حور تعلا حي الشعب , حور تعلا حي الوادي , حور تعلا حي حقل العرجة", en: "Hourtala" },
          { slug: "jabba", ar: "جبعا", en: "Jabba" },
          { slug: "jaboule_et_al_bijage", ar: "جبوله", en: "Jaboulé et Al-Bijage" },
          { slug: "karha", ar: "قرحا", en: "Karha" },
          { slug: "kfardan", ar: "كفردان , كفردان الغربي", en: "Kfardan" },
          { slug: "khreibe", ar: "الخريبه حي الجامع", en: "Khreibé" },
          { slug: "ksarnaba", ar: "قصرنبا", en: "Ksarnaba" },
          { slug: "maaraboun", ar: "معربون", en: "Maaraboun" },
          { slug: "majdeloun", ar: "مجدلون", en: "Majdeloun" },
          { slug: "maqne", ar: "مقنه", en: "Maqné" },
          { slug: "mazraet_beit_mcheik", ar: "بيت مشيك", en: "Mazraet Beit Mcheik" },
          { slug: "mikrak", ar: "مقراق", en: "Mikrak" },
          { slug: "nabha", ar: "نبحا الحرفوش , نبحا الدمدوم , نبحا المحفارة , نبحا حي الجامع", en: "Nabha" },
          { slug: "nabi_sbate", ar: "النبي سباط", en: "Nabi Sbate" },
          { slug: "nahle", ar: "نحله", en: "Nahlé" },
          { slug: "riha", ar: "ريحا", en: "Riha" },
          { slug: "sbouba", ar: "صبوبا", en: "Sbouba" },
          { slug: "serraaine_el_faouka", ar: "سرعين الفوقا حي الجامع , سرعين الفوقا حي الحارة , سرعين الفوقا شرقي , سرعين الفوقا غربي", en: "Serraaine El Faouka" },
          { slug: "serraaine_el_tahta", ar: "سرعين التحتا", en: "Serraaine El Tahta" },
          { slug: "talia", ar: "طليا", en: "Talia" },
          { slug: "tamnine_el_tahta", ar: "تمنين التحتا", en: "Tamnine El-Tahta" },
          { slug: "tamnine_el_fauqa", ar: "تمنين الفوقا", en: "Tamnine-el-Fauqa" },
          { slug: "taraya", ar: "طاريا الجنوبي , طاريا الشمالي", en: "Taraya" },
          { slug: "tfeil", ar: "طفيل", en: "Tfeil" },
          { slug: "yahfoufa", ar: "يحفوفا", en: "Yahfoufa" },
          { slug: "yamoune", ar: "اليمونه", en: "Yamouné" },
          { slug: "yat", ar: "ايعات", en: "Yât" },
          { slug: "younine", ar: "يونين جنوبي , يونين شرقي , يونين شمالي , يونين غربي", en: "Younine" },
          { slug: "zaboud", ar: "زبود", en: "Zaboud" },
        ],
      },
      {
        qada: { slug: "hermel", ar: "الهرمل", en: "Hermel" },
        villages: [
          { slug: "al_kharayeb", ar: "الخرايب", en: "Al-Kharayeb" },
          { slug: "halbata", ar: "حلبتا", en: "Halbata" },
          { slug: "hermel", ar: "الهرمل حي الحارة", en: "Hermel" },
          { slug: "hermel_charbine", ar: "الشربين", en: "Hermel Charbine" },
          { slug: "ouadi_faara", ar: "وادي فعرة", en: "Ouadi Faara" },
        ],
      },
    ],
  },
  {
    mohafaza: { slug: "akkar", ar: "عكار", en: "Akkar" },
    qadas: [
      {
        qada: { slug: "akkar", ar: "عكار", en: "Akkar" },
        villages: [
          { slug: "aaouainat", ar: "العوينات", en: "Aaouainat" },
          { slug: "aidamoun_shikhlar", ar: "عيدمون", en: "Aidamoun shikhlar" },
          { slug: "ain_el_zeit", ar: "عين الزيت", en: "Aïn El-Zeit" },
          { slug: "ain_tanta", ar: "عين تنتا", en: "Aïn Tanta" },
          { slug: "ain_yacoub", ar: "عين يعقوب", en: "Aïn-Yacoub" },
          { slug: "akkar_el_atika", ar: "عكار العتيقه", en: "Akkar El-Atika" },
          { slug: "akroum", ar: "اكروم", en: "Akroum" },
          { slug: "al_abboudie", ar: "العبده", en: "Al-Abboudié" },
          { slug: "al_kharnoube", ar: "الخرنوب", en: "Al-Kharnoubé" },
          { slug: "al_khraibe", ar: "الخريبه", en: "Al-Khraibé" },
          { slug: "al_kneisse", ar: "الكنيسه", en: "Al-Kneissé" },
          { slug: "al_mehamra", ar: "المحمرة", en: "Al-Mehamra" },
          { slug: "al_rihanie", ar: "الريحان", en: "Al-Rihanié" },
          { slug: "al_sammounie", ar: "السمونيه", en: "Al-Sammounié" },
          { slug: "al_semmakie", ar: "السماقية", en: "Al-Semmakié" },
          { slug: "al_souaisse", ar: "السويسه", en: "Al-Souaissé" },
          { slug: "andeket", ar: "عندقت", en: "Andeket" },
          { slug: "arida", ar: "العريضه", en: "Arida" },
          { slug: "arka", ar: "عرقا", en: "Arka" },
          { slug: "barbara", ar: "برباره", en: "Barbara" },
          { slug: "bazbina", ar: "بزبينا", en: "Bazbina" },
          { slug: "bebnine", ar: "ببنين", en: "Bebnine" },
          { slug: "beino", ar: "بينو", en: "Beino" },
          { slug: "beit_ayoub", ar: "بيت ايوب", en: "Beit Ayoub" },
          { slug: "beit_mallat", ar: "بيت ملات", en: "Beit Mallat" },
          { slug: "beit_younes", ar: "بيت يونس", en: "Beit Younes" },
          { slug: "beit_el_haouche", ar: "بيت الحوش", en: "Beit-El-Haouche" },
          { slug: "beit_ghattas", ar: "بيت غطاس", en: "Beit-Ghattas" },
          { slug: "berkayel", ar: "برقايل", en: "Berkayel" },
          { slug: "bkarzala", ar: "بقرزلا", en: "Bkarzala" },
          { slug: "bzal", ar: "بزال", en: "Bzal" },
          { slug: "chakdouf", ar: "الشقدوف", en: "Chakdouf" },
          { slug: "chane", ar: "شان", en: "Chane" },
          { slug: "charbila", ar: "شربيلا", en: "Charbila" },
          { slug: "cheikh_mohamed", ar: "الشيخ محمد", en: "Cheikh Mohamed" },
          { slug: "cheikh_taba_montagne", ar: "الشيخ طابا", en: "Cheikh Taba Montagne" },
          { slug: "cheikh_taba_plaine", ar: "حكر الشيخ طابا", en: "Cheikh Taba Plaine" },
          { slug: "cheikh_zennad_tal_bibe", ar: "الشيخ زناد", en: "Cheikh Zennad Tal Bibé" },
          { slug: "chikhlar", ar: "شيخلار", en: "Chikhlar" },
          { slug: "dabbabiye_charkie", ar: "الدبابيه", en: "Dabbabiyé Charkié" },
          { slug: "dahr_leycine", ar: "ضهر ليسينه", en: "Dahr-Leyciné" },
          { slug: "daoura", ar: "الدوره", en: "Daoura" },
          { slug: "deir_daloum", ar: "دير دلوم", en: "Deir-Daloum" },
          { slug: "deir_janine", ar: "دير جنين", en: "Deir-Janine" },
          { slug: "deirine", ar: "دارين", en: "Deirine" },
          { slug: "douair_adouiye", ar: "دوير عدويه", en: "Douair Adouiyé" },
          { slug: "edbel", ar: "عدبل", en: "Edbel" },
          { slug: "el_bire", ar: "البيره", en: "El-Biré" },
          { slug: "el_borge", ar: "البرج", en: "El-Borge" },
          { slug: "el_daghle", ar: "الدغلي", en: "El-Daghlé" },
          { slug: "el_haouchab", ar: "حوشب", en: "El-Haouchab" },
          { slug: "el_hed", ar: "الهد", en: "El-Hed" },
          { slug: "el_houaiche", ar: "الحوش", en: "El-Houaïche" },
          { slug: "el_karkaf", ar: "القرقف", en: "El-Karkaf" },
          { slug: "el_koubayet", ar: "القبيات", en: "El-Koubayet" },
          { slug: "el_kousseir", ar: "القصير", en: "El-Kousseir" },
          { slug: "el_krayat", ar: "القريات", en: "El-Krayat" },
          { slug: "el_tleil", ar: "التليل", en: "El-Tleil" },
          { slug: "elayoune", ar: "العين", en: "ElAyoune" },
          { slug: "eyoune_el_ghouzlane", ar: "عيون الغزلان", en: "Eyoune-El-Ghouzlane" },
          { slug: "fneidek", ar: "فنيدق", en: "Fneidek" },
          { slug: "freidice", ar: "فريديس", en: "Freidice" },
          { slug: "habchite", ar: "حبشيت", en: "Habchite" },
          { slug: "halba", ar: "حلبا", en: "Halba" },
          { slug: "harare", ar: "حرار", en: "Harare" },
          { slug: "haytla", ar: "هيتلا", en: "Haytla" },
          { slug: "hayzouk", ar: "حيزوق", en: "Hayzouk" },
          { slug: "hekr_el_dahiri", ar: "حكر الضاهري", en: "Hekr el Dahiri" },
          { slug: "hmais", ar: "حميص", en: "Hmais" },
          { slug: "hnaider", ar: "حنيدر", en: "Hnaïder" },
          { slug: "homeira", ar: "الحميره", en: "Homeira" },
          { slug: "iate", ar: "عيات", en: "Iate" },
          { slug: "ilate", ar: "ايلات", en: "Ilate" },
          { slug: "jebrail", ar: "جبرايل", en: "Jebrâil" },
          { slug: "kachlak", ar: "قشلق", en: "Kachlak" },
          { slug: "karem_asfour_el_nahrieh", ar: "كرم عصفور", en: "Karem-Asfour-El-Nahrieh" },
          { slug: "kboula", ar: "قبولا", en: "Kboula" },
          { slug: "kefr_el_ftouh", ar: "كفر الفتوح", en: "Kefr El-Ftouh" },
          { slug: "kfar_harra", ar: "كفر حره", en: "Kfar Harra" },
          { slug: "kfarnoune", ar: "كفرنون", en: "Kfarnoune" },
          { slug: "kfartun", ar: "كفرتون", en: "Kfartun" },
          { slug: "kherbet_char", ar: "خربة شار", en: "Kherbet Char" },
          { slug: "kherbet_daoud", ar: "خربة داوود", en: "Kherbet Daoud" },
          { slug: "kloud_el_bakia", ar: "قلود الباقية", en: "Kloud El-Bakia" },
          { slug: "kobbet_bchamra", ar: "قبة بشمرا", en: "Kobbet Bchamra" },
          { slug: "koueikhat", ar: "كويخات", en: "Koueikhat" },
          { slug: "kroum_arabe", ar: "كروم عرب", en: "Kroum Arabe" },
          { slug: "machha", ar: "مشحا", en: "Machha" },
          { slug: "machta_hammoud", ar: "مشتى حمود", en: "Machta Hammoud" },
          { slug: "machta_hassan", ar: "مشتى حسن", en: "Machta Hassan" },
          { slug: "majdla", ar: "مجدلا", en: "Majdla" },
          { slug: "mar_touma", ar: "مار توما", en: "Mar Touma" },
          { slug: "mazraat_balde", ar: "مزرعة بلده", en: "Mazraat Baldé" },
          { slug: "mechailha_hakour", ar: "مشيلحة حاكوره", en: "Mechaïlha Hakour" },
          { slug: "michmiche", ar: "مشمش", en: "Michmiche" },
          { slug: "mimnih", ar: "ممنع", en: "Mimnih" },
          { slug: "minyara", ar: "منياره", en: "Minyara" },
          { slug: "mounjez", ar: "منجز", en: "Mounjez" },
          { slug: "mqaibleh", ar: "المقيبله", en: "Mqaibleh" },
          { slug: "noura_el_faouka_et_tahta", ar: "النورة", en: "Noura El-Faouka et Tahta" },
          { slug: "omar_el_beikate", ar: "عمار البيكات", en: "Omar el-Beikate" },
          { slug: "ouadi_el_jamous", ar: "وادي الجاموس", en: "Ouadi El-Jamous" },
          { slug: "ouadi_khaled", ar: "وادي خالد", en: "Ouadi Khaled" },
          { slug: "qabbait", ar: "قبعيت", en: "Qabbait" },
          { slug: "rahbe", ar: "رحبه", en: "Rahbé" },
          { slug: "rmah", ar: "رماح", en: "Rmah" },
          { slug: "saadine", ar: "سعدين", en: "Saadine" },
          { slug: "saissouk", ar: "سيسوق", en: "Saïssouk" },
          { slug: "sfeinite_el_dreibe", ar: "سفينة الدريب", en: "Sfeinite El-Dreibe" },
          { slug: "shadra", ar: "شدره", en: "Shadra" },
          { slug: "sindianet_zeidan", ar: "السنديانة", en: "Sindianet Zeidan" },
          { slug: "srar", ar: "سرار", en: "Srar" },
          { slug: "tal_abbas_el_charkie", ar: "تل عباس شرقي", en: "Tal Abbas El-Charkié" },
          { slug: "tal_abbas_el_gharbie", ar: "تل عباس غربي", en: "Tal Abbas El-gharbié" },
          { slug: "tal_bire", ar: "تلبيره", en: "Tal Biré" },
          { slug: "tal_homeira", ar: "تلحميره", en: "Tal Homeira" },
          { slug: "telle_et_chattaha", ar: "تله وشطاحه", en: "Tellé et Chattaha" },
          { slug: "tikrite", ar: "تكريت", en: "Tikrite" },
          { slug: "tshea", ar: "تاشع", en: "Tshea" },
          { slug: "wadi_el_haour", ar: "وادي الحور", en: "Wadi el-Haour" },
          { slug: "zouk_el_moukacherine", ar: "زوق المقشرين", en: "Zouk el Moukachérine" },
          { slug: "zouk_el_habalca", ar: "زوق الحبالصه", en: "Zouk-El-Habalça" },
        ],
      },
    ],
  },
];

// ============================================================
// Derived lookup maps (computed once at module load)
// ============================================================

/** Flat list of all district slugs */
export const ALL_DISTRICTS = LEBANON_DIVISIONS.flatMap((m) =>
  m.qadas.map((q) => q.qada.slug)
);

/** Map from mohafaza slug to its district slugs */
export const DISTRICTS_BY_MOHAFAZA: Record<string, string[]> = Object.fromEntries(
  LEBANON_DIVISIONS.map((m) => [
    m.mohafaza.slug,
    m.qadas.map((q) => q.qada.slug),
  ])
);

/** Map from district slug to its mohafaza slug */
export const MOHAFAZA_BY_DISTRICT: Record<string, string> = Object.fromEntries(
  LEBANON_DIVISIONS.flatMap((m) =>
    m.qadas.map((q) => [q.qada.slug, m.mohafaza.slug])
  )
);

/** Lookup district info by slug */
export const DISTRICT_INFO: Record<string, Division> = Object.fromEntries(
  LEBANON_DIVISIONS.flatMap((m) =>
    m.qadas.map((q) => [q.qada.slug, q.qada])
  )
);

/** Flat list of all village slugs */
export const ALL_VILLAGES = LEBANON_DIVISIONS.flatMap((m) =>
  m.qadas.flatMap((q) => q.villages.map((v) => v.slug))
);

/** Map from district slug to its village slugs */
export const VILLAGES_BY_DISTRICT: Record<string, string[]> = Object.fromEntries(
  LEBANON_DIVISIONS.flatMap((m) =>
    m.qadas.map((q) => [q.qada.slug, q.villages.map((v) => v.slug)])
  )
);

/** Map from village slug to its district slug */
export const DISTRICT_BY_VILLAGE: Record<string, string> = Object.fromEntries(
  LEBANON_DIVISIONS.flatMap((m) =>
    m.qadas.flatMap((q) => q.villages.map((v) => [v.slug, q.qada.slug]))
  )
);

/** Lookup village info by slug */
export const VILLAGE_INFO: Record<string, Division> = Object.fromEntries(
  LEBANON_DIVISIONS.flatMap((m) =>
    m.qadas.flatMap((q) => q.villages.map((v) => [v.slug, v]))
  )
);

/** Lookup any division (mohafaza, district, or village) info by slug */
const ALL_DIVISIONS: Record<string, Division> = {
  ...Object.fromEntries(LEBANON_DIVISIONS.map((m) => [m.mohafaza.slug, m.mohafaza])),
  ...DISTRICT_INFO,
  ...VILLAGE_INFO,
};

/**
 * Get localized name for any slug (mohafaza, district, or village).
 * Falls back to the slug itself if not found.
 */
export function getLocalizedName(slug: string, locale: "ar" | "en"): string {
  const div = ALL_DIVISIONS[slug];
  return div ? div[locale] : slug;
}
